name       : ark
version    : 24.01.90
release    : 78
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/ark-24.01.90.tar.xz : c28a6818f40904de0eae7cbc7d1f27e17b4cb0d4a05f4324ed53ca52d960ccb9
homepage   : https://kde.org/applications/utilities/org.kde.ark
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : A graphical file compression/decompression utility
description: |
    Ark is a graphical file compression/decompression utility with support for multiple formats, including tar, gzip, bzip2, rar and zip, as well as CD-ROM images.
optimize   : lto
builddeps  :
    - pkgconfig(bzip2)
    - pkgconfig(libarchive)
    - pkgconfig(libunarr)
    - pkgconfig(libzip)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kiconthemes-devel
    - kf6-kitemmodels-devel
    - kf6-kparts-devel
    - kf6-kpty-devel
rundeps    :
    - unrar
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
