name       : python-astroid
version    : 3.3.5
release    : 36
source     :
    - https://github.com/pylint-dev/astroid/archive/refs/tags/v3.3.5.tar.gz : cf0c065acb7f3dc61f045ec6fddf247084277a3db527969bae375bccc03ed110
homepage   : https://github.com/PyCQA/astroid
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A common base representation of python source code for pylint and other projects
description: |
    The aim of this module is to provide a common base representation of python source code. It is currently the library powering pylint's capabilities.
builddeps  :
    - python-build
    - python-installer
    - python-wheel
checkdeps  :
    - numpy
    - python-attrs
    - python-dateutil
    - python-lazy-object-proxy
    - python-nose
    - python-pytest
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest
