name       : frameworkintegration
version    : 5.115.0
release    : 75
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/frameworkintegration-5.115.0.tar.xz : 6e299a572cf123a2d2492a5e957d3a21b15039515d9232a34c5e4cbea391636e
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-only
component  : programming.library
summary    : Integration of Qt application with KDE workspaces
description: |
    Framework Integration is a set of plugins responsible for better integration of Qt applications when running on a KDE Plasma workspace.
optimize   : lto
builddeps  :
    - attica-devel
    - ki18n-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - kpackage-devel
    - kservice-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
        - kiconthemes-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
