name       : cava
version    : 0.10.3
release    : 16
source     :
    - https://github.com/karlstav/cava/archive/refs/tags/0.10.3.tar.gz : bf822ac18ae0ca2cf926c2875f3221591960c25f2bcab89ea19729be4b9c3663
homepage   : https://github.com/karlstav/cava
license    : MIT
component  : multimedia.audio
summary    : Console-based Audio Visualizer for Alsa
description: |
    Cava is a bar spectrum audio visualizer for terminal (ncurses) or desktop (SDL).
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(iniparser)
    - pkgconfig(libpulse)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
