name       : element
version    : 1.11.85
release    : 186
homepage   : https://element.io/
source     :
    - git|https://github.com/vector-im/element-desktop.git : 1bdef576fa0bd3b4b5734535ab2f8af264bc737f
    - git|https://github.com/vector-im/element-web.git : bbe474ae578d1f2152f57093d744321a24811279
license    : Apache-2.0
component  : network.im
networking : yes
summary    : A glossy Matrix collaboration client for desktop.
description: |
    All-in-one secure chat app for teams, friends and organisations. Keeps conversations in your control, safe from data-mining and ads. Talk to everyone through the open global Matrix network, protected by proper end-to-end encryption.
replaces   :
    - riot
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atspi-2)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libeconf)
    - pkgconfig(libsecret-1)
    - pkgconfig(pango)
    - pkgconfig(sqlcipher)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - git
    - jq
    - libxcrypt-compat
    - rust
    - yarn
rundeps    :
    - libsecret
    - sqlcipher
setup      : |
    # Copy element-web to the build directory
    cp -a $sources/element-web.git element-web

    # Disable updates/tracking, enable labs settings
    jq '.update_base_url = null | .posthog = null | .show_labs_settings = true' \
        element.io/release/config.json > config.json

    # Ensure that autolaunch files specify the direct path to the wrapper script
    %patch -p1 -i $pkgfiles/autolaunch.patch

    # Unpack the package.json so we can fix the Wayland AppID
    %patch -p1 -i $pkgfiles/0001-Unpack-package.json.patch

    # Perform yarn install on both
    yarn install --frozen-lockfile --network-timeout 180000
    yarn --cwd element-web install --frozen-lockfile --network-timeout 180000
build      : |
    # Build element-web
    yarn --cwd element-web build

    # Build element-desktop
    yarn run build:native
    yarn run build
install    : |
    # Installdir for Element
    element_installdir=$installdir/usr/share/element

    install -dm00644 $element_installdir
    cp -Rv dist/linux-unpacked/* $element_installdir
    cp -Rv element-web/webapp $element_installdir/resources/

    # Wrapper script
    install -Dm00755 $pkgfiles/electron-desktop.sh $installdir/usr/bin/element-desktop

    # Install configuration
    install -Dm00644 config.json $element_installdir/resources/webapp/

    # Install Icons
    for icon_size in 16 24 48 64 96 128 256 512
    do
        install -Dm00644 build/icons/${icon_size}x${icon_size}.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/element-desktop.png
        # Symlink for existing .desktop files
        ln -s element-desktop.png $installdir/usr/share/icons/hicolor/${icon_size}x${icon_size}/apps/element.png
    done

    # Fix Wayland appid
    package_json=$element_installdir/resources/app.asar.unpacked/package.json
    tmp=$(mktemp)
    jq ".desktopName = \"Element.desktop\"" $package_json > "$tmp" && mv "$tmp" $package_json
    chmod 644 $package_json

    # Desktop File
    install -Dm00644 $pkgfiles/Element.desktop $installdir/usr/share/applications/Element.desktop

    # appstream data
    install -Dm00644 $pkgfiles/element.appdata.xml $installdir/usr/share/metainfo/element.appdata.xml
