name       : kdecoration
version    : 5.92.0
release    : 92
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kdecoration-5.92.0.tar.xz : a9af0b4a78e5f4fee3dcf5fd75160c149324709bce94a6537b92e62cf0c76614
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : programming
summary    : Plugin based library to create window decorations
description: |
    Plugin based library to create window decorations.
optimize   : lto
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
