name       : brave
version    : 1.73.89
release    : 213
source     :
    - https://github.com/brave/brave-browser/releases/download/v1.73.89/brave-browser_1.73.89_amd64.deb : f5ed33312e6471331dc64befab6e3c9190d0a41cff1dfe0e314759e258260d5f
homepage   : https://brave.com
license    :
    - GPL-2.0-or-later # Privacy Badger
    - GPL-3.0-or-later # Https Everywhere
    - MPL-2.0
component  : network.web.browser
summary    : A browser focused on privacy that blocks ads and trackers by default
description: |
    Brave is a free and open-source web browser developed by Brave Software, Inc. based on the Chromium web browser. It blocks ads and website trackers, and provides a way for users to send cryptocurrency contributions in the form of Basic Attention Tokens (BAT) to websites and content creators along with the ability to keep the cryptocurrency they earned.
patterns   : /*
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt6Core)
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(cups)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
rundeps    :
    - libgnome-keyring
setup      : |
    ar x $sources/brave-browser_${version}_amd64.deb
    tar xf data.tar.*
    mv usr/share/man/man1/brave-browser-stable.1.gz usr/share/man/man1/brave-browser.1.gz
install    : |
    mkdir -p $installdir
    cp -r usr $installdir/
    cp -r opt/brave.com/brave $installdir/usr/share/
    ln -sfn /usr/share/brave/brave $installdir/usr/bin/brave-browser
    install -Dm00644 opt/brave.com/brave/product_logo_128.png $installdir/usr/share/pixmaps/brave-browser.png
    # Fix broken screenshot
    sed -i 's|https://www.brave.com/images/browser.png|https://raw.githubusercontent.com/flathub/com.brave.Browser/master/screenshot_mainpage.jpg|g' $installdir/usr/share/appdata/brave-browser.appdata.xml

    # Remove stuff that aren't necessary on Solus
    sed -i 's/brave-browser-stable/brave-browser/g' $installdir/usr/share/applications/brave-browser.desktop
    rm -f $installdir/usr/bin/brave-browser-stable
    rm -f $installdir/usr/share/brave/LICENSE
