name       : libmongoc
version    : 1.29.0
release    : 13
source     :
    - https://github.com/mongodb/mongo-c-driver/releases/download/1.29.0/mongo-c-driver-1.29.0.tar.gz : e3dbe86e1f40e100344c48a4c0e39d2da360d2b12a54f16031fa8f90ff16fe5e
homepage   : https://docs.mongodb.com/drivers/c/
license    : Apache-2.0
component  : programming.library
summary    : A high-performance MongoDB driver for C
description: |
    The MongoDB C Driver, also known as libmongoc, is a library for using MongoDB from C applications, and for writing MongoDB drivers in higher-level languages.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(libutf8proc)
    - pkgconfig(libzstd)
    - pkgconfig(snappy)
setup      : |
    %cmake_ninja -DENABLE_STATIC=OFF -DENABLE_TESTS=OFF -DENABLE_ZLIB=SYSTEM -DENABLE_ZSTD=ON -DUSE_BUNDLED_UTF8PROC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share
