name       : zlib
version    : 2.1.6
release    : 28
source     :
    - https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.1.6.tar.gz : a5d504c0d52e2e2721e7e7d86988dec2e290d723ced2307145dedd06aeb6fef2
homepage   : https://github.com/zlib-ng/zlib-ng
license    : ZLIB
component  : system.base
summary    : zlib replacement with optimizations for next generation systems.
description:
    - A zlib data compression library for the next generation systems. ABI/API compatible mode.
devel      : yes
emul32     : yes
optimize   :
    - speed
    - lto
setup      : |
    patch -p1 -R -i $pkgfiles/cmake-tests.patch
    %cmake_ninja \
        -DZLIB_COMPAT=ON \
        -DWITH_GTEST=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DINSTALL_LIB_DIR=%libdir% \
        -DINSTALL_UTILS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
patterns   :
    - devel :
        - /usr/bin/*
