name       : bitwarden-cli
version    : 2024.11.0
release    : 18
source     :
    - https://github.com/bitwarden/clients/archive/refs/tags/cli-v2024.11.0.tar.gz : a55f2add020c51ebf2376c0a5f8fcdec2fd9c0164c61bc9162a778f1edd5f27c
homepage   : https://bitwarden.com/help/cli/
license    : GPL-3.0-only
component  : security
summary    : CLI client for Bitwarden
description: CLI client for Bitwarden, a secure and free password manager for all of your devices
networking : yes
strip      : no
debug      : no
builddeps  :
    - git
    - nodejs-22
environment: |
    export npm_config_build_from_source=true

    # npm is called recursively and we need that to use nodejs-22
    export PATH=/usr/lib64/nodejs-22/bin:$PATH
setup      : |
    npm-22 ci
build      : |
    cd apps/cli

    npm-22 run dist:oss:lin

    node-22 ./build/bw.js completion --shell zsh > _bw
install    : |
    cd apps/cli

    install -Dm00755 dist/oss/linux/bw $installdir/usr/bin/bw
    install -Dm00644 _bw $installdir/usr/share/zsh/site-functions/_bw
