name       : matplotlib
version    : 3.9.2
release    : 43
source     :
    - https://github.com/matplotlib/matplotlib/archive/refs/tags/v3.9.2.tar.gz : 9c49b6683a34469e6d20864c7d5b975c4f29d7c60de1ce857980bead48769c3f
homepage   : https://matplotlib.org/
license    : Python-2.0
component  : programming.python
summary    : Python plotting library
description: |
    matplotlib strives to produce publication quality 2D graphics for interactive graphing, scientific publishing, user interface development and web application servers targeting multiple user interfaces and hardcopy output formats. There is a ‘pylab’ mode which emulates matlab graphics.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(python3)
    - pkgconfig(qhull_r)
    - pkgconfig(tk)
    - pkgconfig(x11)
    - numpy
    - pybind11
    - python-certifi
    - python-setuptools-scm-git-archive
    - python3-tkinter
rundeps    :
    - cycler
    - pyparsing
    - python-contourpy
    - python-dateutil
    - python-fonttools
    - python-kiwisolver
    - python-packaging
    - python-pillow
    - python3-tkinter
setup      : |
    # Use system freetype
    sed -i "s|option('system-freetype', type: 'boolean', value: false,|option('system-freetype', type: 'boolean', value: true,|" meson.options
    sed -i "s|option('system-qhull', type: 'boolean', value: false,|option('system-qhull', type: 'boolean', value: true,|" meson.options
    %meson_configure
build      : |
    export CFLAGS="$CFLAGS -I/usr/include"
    %ninja_build
install    : |
    %ninja_install
