name       : lxc
version    : 6.0.2
release    : 23
source     :
    - https://linuxcontainers.org/downloads/lxc/lxc-6.0.2.tar.gz : 1930aa10d892db8531d1353d15f7ebf5913e74a19e134423e4d074c07f2d6e8b
license    : LGPL-2.1-or-later
component  : virt
homepage   : https://linuxcontainers.org/lxc
summary    : Linux Containers
description: |
    LXC is the well known set of tools, templates, library and language bindings. It's pretty low level, very flexible and covers just about every containment feature supported by the upstream kernel.
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(libapparmor)
    - pkgconfig(libcap)
    - pkgconfig(libseccomp)
    - pkgconfig(python3)
    - docbook2x
rundeps    :
    - dnsmasq
setup      : |
    sed -i "s|if sanitize == 'none'|if false|g" src/lxc/cmd/meson.build

    %meson_configure -Ddistrosysconfdir=/etc/default
build      : |
    %ninja_build
install    : |
    %ninja_install

    # No static libs
    rm -v $installdir/%libdir%/lib*.a

    # Stateless
    install -Dm00644 $pkgfiles/lxc.tmpfiles $installdir/usr/lib/tmpfiles.d/lxc.conf
    # rm -v $installdir/etc/default/lxc \
    #       $installdir/etc/lxc/default.conf
    rmdir -v $installdir/var/cache/lxc \
             $installdir/var/cache \
             $installdir/var/lib/lxc \
             $installdir/var/lib \
             $installdir/var
