name       : gstreamer-vaapi
version    : 1.24.9
release    : 33
source     :
    - https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.24.9.tar.xz : c2373e9b4d6655535d355207f60084b0fb3b28566fe9bb4ca1da714439da4ae1
license    : LGPL-2.1-or-later
component  : multimedia.gstreamer
homepage   : https://gstreamer.freedesktop.org
summary    : VAAPI backend for GStreamer
description: |
    A collection of GStreamer plugins to let you make use of VA API video
    acceleration from GStreamer applications.

    Includes elements for video decoding, display, encoding and post-processing
    using VA API (subject to hardware limitations).
builddeps  :
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xrandr)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
