name       : xdg-desktop-portal-hyprland
version    : 1.3.8
release    : 3
source     :
    - https://github.com/hyprwm/xdg-desktop-portal-hyprland/archive/refs/tags/v1.3.8.tar.gz : 05333efe1dd4f0e1ea4713686438f102b2eb845ca3fc27467dc84c254df7f021
homepage   : https://github.com/hyprwm/xdg-desktop-portal-hyprland
license    : BSD-3-Clause
component  : desktop-hyprland
summary    : xdg-desktop-portal backend for hyprland
description: |
    xdg-desktop-portal backend for hyprland
builddeps  :
    - pkgconfig(Qt6Widgets)
    - pkgconfig(gbm)
    - pkgconfig(hyprland-protocols)
    - pkgconfig(hyprlang)
    - pkgconfig(hyprutils)
    - pkgconfig(hyprwayland-scanner)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libspa-0.2)
    - pkgconfig(sdbus-c++)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
