name       : discord
version    : 0.0.74
release    : 91
source     :
    - https://dl.discordapp.net/apps/linux/0.0.74/discord-0.0.74.tar.gz : c9fda02ef0e0cc5d77720a4a1628821c661547ea7b8d9380477ecbd45e8c66f7
license    : Distributable
component  : network.im
homepage   : https://discord.com/
summary    : All-in-one voice and text chat for gamers
description: |
    All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
replaces   :
    - discord-canary
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xshmfence)
rundeps    :
    - libayatana-appindicator
    - llvm
    - opus
# strip and debug will prevent krisp noise supression from loading
strip      : no
debug      : no
install    : |
    install -Dm00644 $pkgfiles/discord.desktop $installdir/usr/share/applications/discord.desktop
    install -Dm00644 discord.png $installdir/usr/share/pixmaps/discord.png
    install -Dm00644 $pkgfiles/discord.appdata.xml $installdir/usr/share/metainfo/discord.appdata.xml

    # Binary
    install -Dm00755 Discord $installdir/usr/share/discord/Discord
    install -Dm00755 $pkgfiles/discord.sh $installdir/usr/bin/discord

    # Assets
    for i in *.pak *.dat *.bin *.png; do
        install -m00644 $i $installdir/usr/share/discord/.
    done
    install -m00755 chrome_crashpad_handler $installdir/usr/share/discord/

    # .so's
    for i in *.so; do
        install -m00755 $i $installdir/usr/share/discord/.
    done

    # Asset dirs
    for i in locales resources; do
        cp -Ra $i $installdir/usr/share/discord/.
    done
