name       : python-torchvision
version    : 0.17.0
release    : 14
source     :
    - https://github.com/pytorch/vision/archive/refs/tags/v0.17.0.tar.gz : 55e395d5c7d9bf7658c82ac633cac2224aa168e1bfe8bb5b2b2a296c792a3500
homepage   : https://pytorch.org/vision
license    : BSD-3-Clause
component  : programming.python
summary    : Datasets, Transforms and Models specific to Computer Vision
description: |
    The torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.
clang      : yes
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - hipsparse-devel
    - hipblas-devel
    - libtorch-devel
    - rocm-hip
    - pytorch
rundeps    :
    - numpy
    - python-pillow
    - python-six
    - python-tqdm
    - pytorch
environment: |
    # This seems to fix the sporadic duplicate symbol linking error
    unset LDFLAGS
    export MAX_JOBS=%YJOBS%

    export ROCM_PATH=/usr
    export HIP_PATH=/usr
    export HIP_COMPILER=clang
    export HIP_RUNTIME=amd
    export HIP_ROCCLR_HOME=/usr/lib64/llvm-rocm
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
    export HIP_CXX_COMPILER=/usr/bin/hipcc
    export DEVICE_LIB_PATH="/usr/lib64/amdgcn/bitcode"
    export PYTORCH_ROCM_ARCH="%AMDGPUTARGETS%"
    # export HIP_CLANG_LAUNCHER=/usr/bin/sccache
setup      : |
    %patch -p1 -i $pkgfiles/ffmpeg-6.patch
    %patch -p1 -i $pkgfiles/ffmpeg-7.patch
install    : |
    %python3_install
