name       : kf6-baloo
version    : 5.248.0
release    : 3
source     :
    - https://download.kde.org/unstable/frameworks/5.248.0/baloo-5.248.0.tar.xz : 9d8a8ae38226a5ff9d71dbc8f725fcc29b11719902e29ffc46615ae5a8636adb
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Baloo provides file searching and indexing
description: |
    Baloo provides file searching and indexing.
builddeps  :
    - pkgconfig(Qt6Quick)
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kfilemetadata-devel
    - kf6-ki18n-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-solid-devel
    - lmdb-devel
rundeps    :
    - devel :
        - kf6-kcoreaddons-devel
        - kf6-kfilemetadata-devel
        - qt6-base-devel
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
