name       : kio-extras
version    : 24.01.90
release    : 113
source     :
    # Hopefully this is temporary, but we need to build this twice until all KDE apps are qt6
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/kio-extras-24.01.90.tar.xz#kio-extras.tar.xz : d9a8b50e974ce51b0e4f49a3d9422a6f763121bb7a7e8d79e43e65b10e8458a0
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/kio-extras-kf5-24.01.90.tar.xz#kio-extras-kf5.tar.xz : d5305bac1d400137c074a6f3afabdf383fd7896b46c644d0d41c23c99e530971
extract    : no
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Additional components to increase the functionality of KIO
description: |
    Additional components to increase the functionality of KIO.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(libimobiledevice-1.0)
    - pkgconfig(libmtp)
    - pkgconfig(libplist-2.0)
    - pkgconfig(libssh)
    - pkgconfig(libtirpc)
    - pkgconfig(phonon4qt5)
    - pkgconfig(phonon4qt6)
    - pkgconfig(smbclient)
    - pkgconfig(taglib)
    - pkgconfig(x11)
    - gperf
    - kactivities-devel
    - kactivities-stats-devel
    - karchive-devel
    - kdbusaddons-devel
    - kdnssd-devel
    - kdoctools-devel
    - kdsoap-qt5-devel
    - kdsoap-qt6-devel
    - kdsoap-ws-discovery-client-devel
    - kf6-karchive-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kdnssd-devel
    - kf6-ki18n-devel
    - kf6-kio-devel
    - kf6-kguiaddons-devel
    - kf6-syntax-highlighting-devel
    - kf6-kcmutils-devel
    - kf6-ktextwidgets-devel
    - kf6-solid-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - plasma-activities-devel
    - plasma-activities-stats-devel
    - qcoro-qt6-devel
    - syntax-highlighting-devel
    # TODO move libkexiv2 before this in the build order
clang      : yes
optimize   : lto
setup      : |
    mkdir kf5 kf6
    tar --strip-components=1 -xf $sources/kio-extras-kf5.tar.xz -C kf5
    %patch -p1 -d kf5 -i $pkgfiles/0001-Don-t-check-for-system-kdsoap-ws-discover-client.patch
    tar --strip-components=1 -xf $sources/kio-extras.tar.xz -C gear

    %cmake_ninja -S kf5 \
                 -B kf5-build \
                 -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF \
                 -DINTERNAL_WSDCLIENT=ON

    %cmake_kf6 -S gear \
               -B gear-build
build      : |
    %ninja_build -C kf5-build
    %ninja_build -C gear-build
install    : |
    %ninja_install -C kf5-build
    %ninja_install -C gear-build

    #remove docs
    rm -rfv $installdir/usr/share/doc
