name       : kcalc
version    : 24.01.90
release    : 68
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/kcalc-24.01.90.tar.xz : 3122c2aedae4c03c5b437f1e6dd966ff043f94a50d4de2a5177d19c053a7e26a
homepage   : https://kde.org/applications/utilities/org.kde.kcalc
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Scientific calculator by KDE
description: |
    KCalc is a calculator which offers many more mathematical functions than meet the eye on a first glance.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(gmp)
    - pkgconfig(Qt6Core5Compat)
    - kf6-kcrash-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
    - kf6-kxmlgui-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
