name       : obs-studio
version    : 30.2.2
release    : 123
source     :
    - git|https://github.com/obsproject/obs-studio.git : 30.2.2
    - https://github.com/FFmpeg/nv-codec-headers/releases/download/n12.1.14.0/nv-codec-headers-12.1.14.0.tar.gz : 62b30ab37e4e9be0d0c5b37b8fee4b094e38e570984d56e1135a6b6c2c164c9f
license    : GPL-2.0-or-later
component  : multimedia.video
homepage   : https://obsproject.com/
summary    : Open Broadcaster Software is free and open source software for video recording and live streaming.
description: |
    Open Broadcaster Software is free and open source software for video recording and live streaming.
libsplit   : no
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(alsa)
    - pkgconfig(asio)
    - pkgconfig(fdk-aac)
    # - pkgconfig(ffnvcodec) # Too new
    - pkgconfig(fontconfig)
    - pkgconfig(jansson)
    - pkgconfig(libavcodec)
    - pkgconfig(libcurl)
    - pkgconfig(libpci)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(librist)
    - pkgconfig(libv4l2)
    - pkgconfig(libva)
    - pkgconfig(libvlc)
    - pkgconfig(luajit)
    - pkgconfig(mbedtls)
    - pkgconfig(nlohmann_json)
    - pkgconfig(python3)
    - pkgconfig(qrcodegencpp)
    - pkgconfig(rnnoise)
    - pkgconfig(speexdsp)
    - pkgconfig(srt)
    - pkgconfig(uthash)
    - pkgconfig(vpl)
    - pkgconfig(wayland-client)
    - pkgconfig(x264)
    - pkgconfig(xcomposite)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon-x11)
    - cef-minimal-devel
    - libdatachannel-devel
    - swig
    - websocketpp
setup      : |
    %patch -p1 -i $pkgfiles/0001-Disable-Werror.patch

    mkdir ffnvcodec
    tar --strip-components=1 -xf $sources/nv-codec*.tar.gz -C ffnvcodec
    mkdir -p ffnvcodec/lib/pkgconfig
    sed "s|@@PREFIX@@|${workdir}/ffnvcodec|g" ffnvcodec/ffnvcodec.pc.in > ffnvcodec/lib/pkgconfig/ffnvcodec.pc
    export CMAKE_PREFIX_PATH="$workdir/ffnvcodec"

    %cmake_ninja \
        -DCEF_ROOT_DIR="/usr/share/cef-minimal" \
        -DENABLE_AJA=OFF \
        -DENABLE_LIBFDK=ON \
        -DOBS_VERSION_OVERRIDE="$version"
build      : |
    %ninja_build
install    : |
    %ninja_install
