name       : ibus
version    : 1.5.29
release    : 30
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.29/ibus-1.5.29-rc2.tar.gz : 3a27ed120485b2077c62e36e788c302f34544ceac3b3b9cda28b7418e8051415
homepage   : https://github.com/ibus/ibus
license    : LGPL-2.0-only
component  : desktop.core
summary    : Intelligent Input Bus
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
builddeps  :
    - pkgconfig(dbusmenu-glib-0.4)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - gnome-common
    - gtk-doc
    - unicode-character-database
    - vala
rundeps    :
    - unicode-character-database
setup      : |
    %apply_patches
    %configure --disable-python2 \
        --disable-silent-rules \
        --disable-static \
        --enable-gtk4 \
        --enable-memconf \
        --enable-gtk-doc \
        --enable-wayland
build      : |
    %make
install    : |
    %make_install
