name       : marp-cli
version    : 4.0.3
release    : 14
homepage   : https://marp.app/
source     :
    - https://github.com/marp-team/marp-cli/archive/refs/tags/v4.0.3.tar.gz : 9d75e2794077611ba0d7808a2a2392bb694730a82999a5108eb822e2b1202db6
license    : MIT
component  : office
summary    : A CLI interface for Marp and Marpit based converters
description: |
    A CLI interface for Marp and any slide deck converter based on Marpit framework. It can convert Marp / Marpit Markdown files into static HTML / CSS, PDF, PowerPoint document, and image(s) easily.
networking : yes
strip      : no
debug      : no
builddeps  :
    - git
    - nodejs
    - yarn
setup      : |
    yarn install
build      : |
    yarn build
    yarn run pkg . \
        --out-path ./bin \
        --targets host \
        --compress Brotli
install    : |
    install -Dm0755 bin/marp-cli $installdir/usr/bin/marp
