name       : font-iosevka-ttf
version    : 32.1.0
release    : 79
source     :
    - https://github.com/be5invis/Iosevka/releases/download/v32.1.0/PkgTTF-Iosevka-32.1.0.zip : cdc60dd471fb2dfdb0a276a06625bc85ff88bbfcbd3228875a643b680e487176
homepage   : https://typeof.net/Iosevka
license    : OFL-1.1
component  : desktop.font
summary    : Versatile typeface for code, from code.
description: |
    Iosevka is an open-source, sans-serif + slab-serif, monospace + quasi-proportional typeface family, designed for writing code, using in terminals, and preparing technical documents.
install    : |
    install -Dm00644 *.ttf -t $installdir/usr/share/fonts/truetype/iosevka/
    install -Dm00644 $pkgfiles/iosevka.metainfo.xml $installdir/usr/share/metainfo/iosevka.metainfo.xml
