name       : gnome-nibbles
version    : 4.1.0
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-nibbles/4.1/gnome-nibbles-4.1.0.tar.xz : 63241bd8a15f59180a61812041e2e8f39862267dc9e652f3d173542c550d9292
homepage   : https://gitlab.gnome.org/GNOME/gnome-nibbles/-/wikis/home
license    : GPL-3.0-or-later
component  : games.arcade
summary    : Guide a worm around a maze
description: |
    Nibbles is a Snake game for GNOME. The aim of the game is to swallow as many objects as you can while avoiding maze walls and other worms. You have to complete 26 levels to finish the game.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gsound)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libgnome-games-support-2)
    - desktop-file-utils
    - itstool
    - vala
    - yelp-tools
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
