name       : python-django
version    : 5.1.3
release    : 23
source     :
    - https://files.pythonhosted.org/packages/source/D/Django/Django-5.1.3.tar.gz : c0fa0e619c39325a169208caef234f90baa925227032ad3f44842ba14d75234a
homepage   : https://www.djangoproject.com
license    : BSD-3-Clause
component  : programming.python
summary    : The Web framework for perfectionists with deadlines
description: |
    Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.
builddeps  :
    - python-build
    - python-installer
    - python-wheel
rundeps    :
    - python-asgiref
    - python-pytz
    - python-sqlparse
setup      : |
    %patch -p1 -i $pkgfiles/0001-Allow-newer-version-of-setuptools.patch
build      : |
    %python3_setup
install    : |
    %python3_install
