name       : lact
version    : 0.6.0
release    : 5
source     :
    - https://github.com/ilya-zlobintsev/LACT/archive/refs/tags/v0.6.0.tar.gz : 09ab15a39e2df1ae6fb8021c79ce979262292d806a6bd57b248ac475e5c9495b
homepage   : https://github.com/ilya-zlobintsev/LACT
license    : MIT
component  : system.utils
summary    : Linux AMDGPU Configuration Tool
networking : yes
clang      : yes
description: |
    This application allows you to control your AMD GPU on a Linux system.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libdrm)
    - blueprint-compiler
    - rust
setup      : |
    %patch -p1 -i $pkgfiles/0001-Solus-Start-after-systemd-udev.patch
    %patch -p1 -i $pkgfiles/0001-Solus-Use-run-instead-of-var-run.patch
    %patch -p1 -i $pkgfiles/0001-solus-Adapt-to-our-amdgpu-kernel-argument.patch
    %patch -p1 -i $pkgfiles/group-priority.patch

    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %make_install PREFIX=/usr
    install -Dm00644 $pkgfiles/io.github.lact.metainfo.xml -t $installdir/usr/share/metainfo/

    # Start service by default
    install -dm00755 $installdir/usr/lib/systemd/system/multi-user.target.wants
    ln -sv ../lactd.service $installdir/usr/lib/systemd/system/multi-user.target.wants/lactd.service

    # Allow amdgpu users to overclock their GPUs by default
    # This only works on our -current kernel for now (remove this note once -lts is >= kernel 6.12)
    install -Dm00644 $pkgfiles/kernel-lact.cmdline $installdir/usr/lib64/kernel/cmdline.d/50_lact.conf
