name       : kwallet
version    : 5.115.0
release    : 79
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kwallet-5.115.0.tar.xz : f2b3fc21c89440c9290703929a8bcb77461fa510fd060c33d64787c9e0eaef3d
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
optimize   : lto
builddeps  :
    - pkgconfig(libgcrypt)
    - pkgconfig(qca2-qt5)
    - gpgme-qt-devel
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
setup      : |
    # Plasma-6: Change BUILD_KWALLETD and BUILD_KWALLET_QUERY
    %cmake_ninja -DBUILD_QCH=ON \
                 -DBUILD_TESTING=OFF \
                 -DBUILD_KWALLETD=ON \
                 -DBUILD_KWALLET_QUERY=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
