name       : onedrive
version    : 2.5.3
release    : 44
source     :
    - https://github.com/abraunegg/onedrive/archive/refs/tags/v2.5.3.tar.gz : 1b385c4f3d34d703e2ed095575244ea03df4bb41fcc7d0d8fbd6366534f2ca6a
homepage   : https://abraunegg.github.io/
license    : GPL-3.0-or-later
component  : network.clients
summary    : A complete tool to interact with OneDrive on Linux.
description: |
    CLI tool to access and update your OneDrive files. Featuring shared folders, support for OneDrive for Business, resumable uploads, real-time file monitoring and state caching.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
    - dmd
setup      : |
    # Remove unneeded "documentation" files
    %patch -p1 -i $pkgfiles/remove_docs.patch

    %reconfigure --enable-completions --with-zsh-completion-dir=/usr/share/zsh/site-functions --with-fish-completion-dir=/usr/share/fish/vendor_completions.d
build      : |
    %make
install    : |
    %make_install
patterns   :
    - /*
