name       : kactivities-stats
version    : 5.115.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kactivities-stats-5.115.0.tar.xz : a4e942c0ba521ef393f4b2c12fbf33fea3bb2f4a0a6a388993b178922d91e666
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Library to access statistics collected by the KDE activity manager
description: |
    The KActivitiesStats library provides a querying mechanism for the data that the activitiy manager collects - which documents hae been opened by which applications, and what documents have been linked to which activity. The activity manager also keeps the score for each document which gets higher when a particular document has been often accessed or kept open for longer periods of time. This score is also available through the querying mechanism.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kactivities-devel
    - kconfig-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
