name       : calamares
version    : 3.3.11
release    : 26
source     :
    - https://github.com/calamares/calamares/releases/download/v3.3.11/calamares-3.3.11.tar.gz : 272f508594852b9b9d322fbe67efc0bdef45362b18c561a622d95323bb83e910
homepage   : https://calamares.io
license    :
    - BSD-2-Clause
    - CC-BY-4.0
    - CC0-1.0
    - GPL-3.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-or-later
    - MIT
component  : system
summary    : Distribution-independent installer framework
description: |
    Calamares is a distribution-independent system installer, with an advanced partitioning feature for both manual and automated partitioning operations. Calamares is designed to be customizable by distribution maintainers without the need for cumbersome patching, thanks to third-party branding and external modules support.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6UiTools)
    - pkgconfig(icu-i18n)
    - pkgconfig(libparted)
    - pkgconfig(polkit-qt6-1)
    - pkgconfig(pwquality)
    - pkgconfig(python3)
    - pkgconfig(yaml-cpp)
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-ki18n-devel
    - kf6-kparts-devel
    - kf6-kwidgetsaddons-devel
    - kpmcore-devel
    - libboost-devel
    - python-jsonschema
rundeps    :
    - rsync
setup      : |
    %apply_patches
    %cmake_ninja -DWITH_QT6:BOOL=true
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -Dm00755 $pkgfiles/calamares-gui $installdir/usr/bin/calamares-gui

    calamares_dir=$installdir/usr/share/calamares
    find $pkgfiles/install -type f|while read fname; do
        install -Dm00644 "$fname" "${calamares_dir}${fname##$pkgfiles/install}"
    done

    install -Dm00644 $pkgfiles/10-livecd.rules $installdir/usr/share/polkit-1/rules.d/10-livecd.rules
