name       : protobuf
version    : '25.3'
release    : 16
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v25.3.tar.gz : d19643d265b978383352b3143f04c0641eea75a75235c111cc01a1350173180e
homepage   : https://developers.google.com/protocol-buffers/
license    : BSD-3-Clause
component  : programming
summary    : Protocol Buffers - Google's data interchange format
description: |
    Protocol Buffers - Google's data interchange format
builddeps  :
    - pkgconfig(absl_base)
checkdeps  :
    - gtest
setup      : |
    %cmake_ninja -D protobuf_BUILD_SHARED_LIBS=ON \
                 -D protobuf_USE_EXTERNAL_GTEST=ON \
                 -D protobuf_ABSL_PROVIDER=package \
                 -W no-dev
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    ctest --test-dir solusBuildDir
