name       : flatpak-kcm
version    : 5.92.0
release    : 6
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/flatpak-kcm-5.92.0.tar.xz : 20f778624024c5720f772f9e91e84c64b02b60eb131bb1cd821109afa90398c0
homepage   : https://invent.kde.org/plasma/flatpak-kcm
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Flatpak Permissions Management KCM
description: |
    Flatpak Permissions Management KCM
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Svg)
    - pkgconfig(flatpak)
    - extra-cmake-modules
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kdeclarative-devel
    - kf6-ki18n-devel
    - kf6-kitemmodels-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/flatpak-discover.svg $installdir/usr/share/icons/hicolor/scalable/apps/flatpak-discover.svg
