name       : pysolfc
version    : 3.1.0
release    : 16
source     :
    - https://sourceforge.net/projects/pysolfc/files/PySolFC/PySolFC-3.1.0/PySolFC-3.1.0.tar.xz : 3dcf1c703b35b446d78a062b2471b138e22926db9d20207373c465144700a0cc
homepage   : https://pysolfc.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club Edition (PySolFC) is a collection of more than 1000 solitaire card games.
rundeps    :
    - pysolfc-cardsets
    - python-attrs
    - python-configobj
    - python-pillow
    - python-pysol-cards
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 $pkgfiles/io.sourceforge.pysolfc.PySolFC.appdata.xml -t $installdir/usr/share/metainfo/
