name       : kde-gtk-config
version    : 5.92.0
release    : 92
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kde-gtk-config-5.92.0.tar.xz : d010a06954e4178bfed295301b8eb37f0c4cf0f77e5c3f79781ceb6cea3433d1
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-2-Clause
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE settings to set GTK look and feel
description: |
    KDE system settings to set GTK look and feel.
optimize   : lto
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(Qt6Svg)
    - gsettings-desktop-schemas
    - kdecoration-devel
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kguiaddons-devel
    - kf6-kwindowsystem-devel
    - sassc
rundeps    :
    - gsettings-desktop-schemas
    - xsettingsd
setup      : |
    %patch -p1 -i $pkgfiles/0002-Use-explicit-path-of-the-gtk-module.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
