name       : python-eopkg
version    : '4.0'
release    : 1
source     :
    - git|https://github.com/getsolus/eopkg.git : 71f90b9e37f7073c3affcd490c64406049bafe8c
homepage   : https://github.com/getsolus/eopkg
license    : GPL-2.0-or-later
component  : programming.python
summary    : eopkg includes (py3)
description: |
    Python3 includes for eopkg package manager (no executables)
builddeps  :
    - python-build
    - python-installer
    - python-lxml
    - python-packaging
    - python-wheel
rundeps    :
    - python-lxml
build      : |
    %python3_setup
install    : |
    %python3_install

    # Remove executables. We use a nuitka compiled version of eopkg as the actual package manager
    # to guard against python3 bootstrap issues.
    rm -fr $installdir/usr/bin/
