name       : tealdeer
version    : 1.7.1
release    : 13
source     :
    - https://github.com/tealdeer-rs/tealdeer/archive/refs/tags/v1.7.1.tar.gz : 2b10e141774d2a50d25a1d3ca3d911dedc0e1313366ce0a364068c7a686300d8
license    : MIT
component  : system.utils
homepage   : https://tldr.sh/
summary    : A very fast implementation of tldr in Rust.
description: |
    A very fast implementation of tldr in Rust: Simplified, example based and community-driven man pages.
networking : yes
builddeps  :
    - rust
setup      : |
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tldr
    cd $workdir/completion
    install -Dm00644 bash_tealdeer $installdir/usr/share/bash-completion/completions/tldr
    install -Dm00644 fish_tealdeer $installdir/usr/share/fish/vendor_completions.d/tldr.fish
    install -Dm00644 zsh_tealdeer $installdir/usr/share/zsh/site-functions/_tealdeer
