name       : tetrs
version    : 0.2.4
release    : 3
source     :
    - https://github.com/Strophox/tetrs/archive/refs/tags/v0.2.4.tar.gz : bcfc83a1b5f4e91021310c6a0fa868466b699a7915c404b10786bae606adb36d
homepage   : https://github.com/Strophox/tetrs
license    : MIT
component  : games.puzzle
summary    : Tetromino Game Engine + Terminal Application
description: |
    Tetromino Game Engine + Terminal Application
networking : yes
builddeps  :
    - rust
setup      : |
    cp $pkgfiles/Cargo.lock ./Cargo.lock
    %cargo_fetch
build      : |
    %cargo_build
install    : |
    %cargo_install tetrs_tui
