name       : ypkg
version    : '32'
release    : 175
source     :
    - git|https://github.com/getsolus/ypkg.git : a05f28351267abc3363c2bb04c66408dbd4ed1fa
homepage   : https://github.com/getsolus/ypkg
license    : GPL-3.0-or-later
component  : system.devel
summary    : Modern, declarative, structured build format
description: |
    ypkg is the build tool of choice for Solus.

    Simply put, it is a tool to convert a build process into a packaging operation.
mancompress: yes
strip      : no
debug      : no
builddeps  :
    - pkgconfig(python3)
    - nuitka
    - patchelf
    - python-zstandard
    - python-eopkg
rundeps    :
    - fakeroot
    - pyyaml
    - python-eopkg
    - ruamel_yaml
environment: |
    # ensure our nuitka build doesn't pull in -v3 hwcaps libs
    export GLIBC_TUNABLES=glibc.cpu.hwcaps=-AVX
setup      : |
    %python3_setup
build      : |
    # build static bins from ypkg
    for b in ypkg ypkg-build ypkg-install-deps ypkg-gen-history ybump yupdate
    do
        # --include-package-data=ypkg is necessary to get rc.yml included (will include all non-py files actually)
        time nuitka3 --onefile --include-module=dbm.gnu --show-scons --no-deployment-flag=self-execution $workdir/$b --include-package-data=ypkg2
    done
install    : |
    %python3_install

    # now override bins with our nuitka'd variants
    for b in ypkg ypkg-build ypkg-install-deps ypkg-gen-history ybump yupdate
    do
        install -Dm0755 $workdir/$b $installdir/usr/bin/$b
    done
