name       : kscreenlocker
version    : 5.92.0
release    : 96
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kscreenlocker-5.92.0.tar.xz : e568840af812976eae4ccc4dc8c42c80dce6950e120dec26ac409d49b380a597
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Library and components for secure lock screen architecture
description: |
    Library and components for secure lock screen architecture.
optimize   : lto
builddeps  :
    - pkgconfig(libseccomp)
    - pkgconfig(pam)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcursor)
    - pkgconfig(xi)
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-ki18n-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
    - kf6-kwindowsystem-devel
    - kf6-kxmlgui-devel
    - kf6-solid-devel
    - layer-shell-qt-devel
    - libkscreen-devel
    - libplasma-devel
    - plasma-kwayland-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/kde $installdir/usr/share/defaults/etc/pam.d/kde
    %qml6_cache
