name       : kinfocenter
version    : 5.92.0
release    : 99
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kinfocenter-5.92.0.tar.xz : f951eed9e5c80b2199366aed18938f33b3ddc2bf90e61fad4265b2d78778f316
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : KDE Info Center
description: |
    KInfoCenter is a utility that provides information about a computer system.
optimize   : lto
builddeps  :
    - pkgconfig(libusb-1.0)
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
rundeps    :
    - aha
    - clinfo
    - fwupd
    - kf6-kirigami
    - plasma-disks
    - vulkan-tools
    - wayland-utils
setup      : |
    %patch -p1 -i $pkgfiles/0001-Use-stateless-directory-for-menu.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rf $installdir/usr/share/doc
    # Fix appstream processing
    install -Dm00644 $workdir/logo.png $installdir/usr/share/icons/hicolor/128x128/apps/hwinfo.png
patterns   :
    - main :
        - /usr/lib64/libKInfoCenterInternal.so
