name       : kwin
version    : 5.92.0
release    : 114
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kwin-5.92.0.tar.xz : c4a167fe6cc613fa6fd73c3697b1d925c42fdc717531a346e0005ba5aef4c17e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-only
component  : desktop.kde.core
summary    : KDE window manager
description: |
    KWin is the window manager for the KDE Plasma Desktop. It gives you complete control over your windows, making sure they're not in the way but aid you in your task. It paints the window decoration, the bar on top of every window with (configurable) buttons like close, maximize and minimize. It also handles placing of windows and switching between them.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Sensors)
    - pkgconfig(Qt6VirtualKeyboard)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gbm)
    - pkgconfig(lcms2)
    - pkgconfig(libcap)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libinput)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libxcvt)
    - pkgconfig(sm)
    - pkgconfig(wayland-cursor)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcb-event)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xi)
    - pkgconfig(xkbcommon)
    - pkgconfig(xorg-server)
    - breeze-devel
    - kdecoration-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-krunner-devel
    - kf6-ksvg-devel
    - kf6-kxmlgui-devel
    - kglobalacceld-devel
    - kscreenlocker-devel
    - libplasma-devel
    - plasma-activities-devel
    - plasma-kwayland-devel
    - plasma-wayland-protocols-devel
    - wayland-protocols-devel
rundeps    :
    - kf6-kirigami
    - libplasma
    - qt6-virtualkeyboard
patterns   :
    - /usr/lib64/libkdeinit5*.so
replaces   :
    - kwayland-server
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rf $installdir/usr/share/doc/HTML
