name       : zafiro-dark-icon-theme
version    : 1.3
release    : 1
source     :
    - https://github.com/zayronxio/Zafiro-icons/releases/download/1.3/Zafiro-Icons-Dark.tar.xz : 7780c0f824eae40cbe167a0ab2f5f2a33be41156c5ea52c789969965264db0b5
homepage   : https://github.com/zayronxio/Zafiro-icons/
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : The Zafiro-Icons
description: |
    Minimalist icons created with the flat-design technique, utilizing washed-out colors and always accompanied by white. The priority is simplicity.
install : |
    mv $workdir/apps/scalable/Î²TORRENT.svg $workdir/apps/scalable/TORRENT.svg
    install -dm00644 $installdir/usr/share/icons/zafiro-icons-dark
    cp -r * $installdir/usr/share/icons/zafiro-icons-dark/
    

    
