name       : zlib-ng
version    : 2.1.6
release    : 29
source     :
    - https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.1.6.tar.gz : a5d504c0d52e2e2721e7e7d86988dec2e290d723ced2307145dedd06aeb6fef2
homepage   : https://github.com/zlib-ng/zlib-ng
license    : ZLIB
component  :
    - programming.library
    - ^zlib : system.base
    - ^zlib-32bit : emul32
    - ^zlib-32bit-devel : programming.devel
    - ^zlib-devel : system.devel
summary    : zlib replacement with optimizations for next generation systems.
description:
    - A zlib data compression library for the next generation systems. ABI/API compatible mode.
emul32     : yes
rundeps    :
    - ^zlib-32bit :
        - zlib
    - ^zlib-32bit-devel :
        - zlib-32bit
        - zlib-devel
    - ^zlib-devel :
        - zlib
optimize   :
    - speed
    - lto
setup      : |
    patch -p1 -R -i $pkgfiles/cmake-tests.patch
    %cmake_ninja -B build-zlib \
        -DZLIB_COMPAT=ON \
        -DWITH_GTEST=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DINSTALL_LIB_DIR=%libdir% \
        -DINSTALL_UTILS=OFF

    # We might not need the 32bit-version of zlib-ng
    if [ -n "${EMUL32BUILD+set}" ]; then
        exit 0
    fi
    %cmake_ninja -B build-zlib-ng \
        -DZLIB_COMPAT=OFF \
        -DWITH_GTEST=OFF \
        -DBUILD_SHARED_LIBS=ON \
        -DINSTALL_LIB_DIR=%libdir% \
        -DINSTALL_UTILS=OFF
build      : |
    %ninja_build -C build-zlib

    if [ -n "${EMUL32BUILD+set}" ]; then
        exit 0
    fi
    %ninja_build -C build-zlib-ng
install    : |
    %ninja_install -C build-zlib

    if [ -n "${EMUL32BUILD+set}" ]; then
        exit 0
    fi
    %ninja_install -C build-zlib-ng
check      : |
    %ninja_check -C build-zlib

    if [ -n "${EMUL32BUILD+set}" ]; then
        exit 0
    fi
    %ninja_check -C build-zlib-ng
patterns   :
    - ^zlib :
        - /usr/lib64/libz.so.1*
    - ^zlib-32bit :
        - /usr/lib32/libz.so.1*
    - ^zlib-32bit-devel :
        - /usr/lib32/cmake/ZLIB/
        - /usr/lib32/libz.so
        - /usr/lib32/pkgconfig/zlib.pc
    - ^zlib-devel :
        - /usr/include/*.h
        - /usr/lib64/cmake/ZLIB/
        - /usr/lib64/libz.so
        - /usr/lib64/pkgconfig/zlib.pc
    - devel :
        - /usr/include/*-ng.h
replaces   :
    - 32bit-dbginfo : zlib-32bit-dbginfo
    - dbginfo : zlib-dbginfo
