name       : plasma-nm
version    : 5.92.0
release    : 95
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-nm-5.92.0.tar.xz : 8399b2ec9d59b105e650ff15a85d0fd3c71414c0bb839d582fcee7e105dbaae4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(ModemManager)
    - pkgconfig(openconnect)
    - pkgconfig(Qt6WebEngineWidgets)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
    - kf6-kwallet-devel
    - kf6-modemmanager-qt-devel
    - kf6-networkmanager-qt-devel
    - kf6-prison-devel
    - libplasma-devel
    - mobile-broadband-provider-info-devel
    - qca-qt6-devel
    - qcoro-qt6-devel
rundeps    :
    - prison
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
