name       : hyprlock
version    : 0.5.0
release    : 3
source     :
    - https://github.com/hyprwm/hyprlock/archive/refs/tags/v0.5.0.tar.gz : 4f8a0199de205ad21a4e3da88c0196514a0ba3c6162e44f93e7cfb96371daf99
homepage   : https://github.com/hyprwm/hyprlock
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : Hyprland's simple, yet multi-threaded and GPU-accelerated screen locking utility.
description: |
    Hyprland's simple, yet multi-threaded and GPU-accelerated screen locking utility.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gbm)
    - pkgconfig(hyprlang)
    - pkgconfig(hyprutils)
    - pkgconfig(libdrm)
    - pkgconfig(libjpeg)
    - pkgconfig(libmagic)
    - pkgconfig(libwebp)
    - pkgconfig(opengl)
    - pkgconfig(pam)
    - pkgconfig(pango)
    - pkgconfig(pangocairo)
    - pkgconfig(sdbus-c++)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-eglstream)
    - pkgconfig(wayland-eglstream-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Stateless
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    mv $installdir/etc/pam.d/hyprlock $installdir/usr/share/defaults/etc/pam.d
    rmdir -v $installdir/etc/pam.d \
             $installdir/etc
