name       : kbookmarks
version    : 5.115.0
release    : 77
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kbookmarks-5.115.0.tar.xz : 164f11a92548c54d4855d207a6a7fa7bd3e7f71f8af01a43899f49c0188cdec0
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - LGPL-2.0-or-later
component  : desktop.library
summary    : Bookmarks management library.
description: |
    Bookmarks management library.
optimize   : lto
builddeps  :
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
