name       : solid
version    : 5.115.0
release    : 78
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/solid-5.115.0.tar.xz : a7a1c6f6a0ef27b876e3753c67ea17ec5cc1d66cfd3e2c0fbba83e2ce4773d7b
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Desktop hardware abstraction.
description: |
    Desktop hardware abstraction.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - media-player-info
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
    - media-player-info
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
