name       : layer-shell-qt
version    : 5.92.0
release    : 26
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/layer-shell-qt-5.92.0.tar.xz : 66fddd39189cca1ea0b13188f976e0cd606079ca9cf81089d276ec316c305af2
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - CC0-1.0
    - LGPL-3.0-or-later
    - MIT
component  : system.utils
summary    : Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
description: |
    Qt component to allow applications to make use of the Wayland wl-layer-shell protocol
builddeps  :
    - pkgconfig(Qt6WaylandCompositor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xkbcommon)
    - plasma-kwayland-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
