name       : python-protobuf
version    : '25.3'
release    : 22
source     :
    - https://github.com/protocolbuffers/protobuf/archive/refs/tags/v25.3.tar.gz : d19643d265b978383352b3143f04c0641eea75a75235c111cc01a1350173180e
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Protocol Buffers are Google’s data interchange format.
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
rundeps    :
    - protobuf
    - python-six
setup      : |
    sed -e 's|c++14|c++20|' -i python/setup.py
build      : |
    pushd python
    # Python macros do not work with this
    python3 setup.py build --cpp_implementation
install    : |
    pushd python
    python3 setup.py install --root="%installroot%" --cpp_implementation
