name       : plasma-integration
version    : 5.92.0
release    : 98
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-integration-5.92.0.tar.xz : dbce852c746d2e2443ddaccc3066959fb206923e4d6b61caf4a50950c6853453
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : Integration of Qt application with KDE workspaces
description: |
    Integration of Qt application with KDE workspaces.
builddeps  :
    - pkgconfig(Qt5QuickControls2)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(xcb)
    - pkgconfig(xcursor)
    - pkgconfig(wayland-server)
    - kf6-ki18n-devel
    - font-hack-ttf
    - kconfig-devel
    - kconfigwidgets-devel
    - kf6-kconfig-devel
    - kf6-kconfigwidgets-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-kwindowsystem-devel
    - kf6-kxmlgui-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwindowsystem-devel
    - kwayland-devel
    - kguiaddons-devel
    - kxmlgui-devel
    - noto-sans-ttf
    - plasma-wayland-protocols-devel
    - xdg-desktop-portal-kde
rundeps    :
    - font-hack-ttf
    - noto-sans-ttf
    - qqc2-desktop-style
    - xdg-desktop-portal-kde
clang      : yes
optimize   : lto
setup      : |
    # TODO Fix patches
    %cmake_kf6 -B qt5-build -DBUILD_QT5=ON -DBUILD_QT6=OFF
    %cmake_kf6 -B qt6-build -DBUILD_QT5=OFF -DBUILD_QT6=ON
build      : |
    %ninja_build -C qt5-build
    %ninja_build -C qt6-build
install    : |
    %ninja_install -C qt5-build
    %ninja_install -C qt6-build
