name       : kxmlgui
version    : 5.115.0
release    : 84
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kxmlgui-5.115.0.tar.xz : 6b712d22d444210f803511daa7792b37ad1f8b29b7bcafee940ef0c06cb3783d
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Framework for managing menu and toolbar actions.
description: |
    Framework for managing menu and toolbar actions.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - kconfig-devel
    - kconfigwidgets-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
rundeps    :
    - devel :
        - kconfigwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
