name       : kdeplasma-addons
version    : 5.92.0
release    : 96
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kdeplasma-addons-5.92.0.tar.xz : 544481b4b62c4b20dd9a6a86d6d9a769039d34e531106bde8dc33d5175b65d3d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Addons for KDE Plasma
description: |
    Addons for KDE Plasma.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(icu-i18n)
    - pkgconfig(x11)
    - kf6-karchive-devel
    - kf6-kcmutils-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-kholidays-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-krunner-devel
    - kf6-kunitconversion-devel
    - kf6-kxmlgui-devel
    - kf6-networkmanager-qt-devel
    - kf6-purpose-devel
    - kf6-sonnet-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
    - plasma5support-devel
    - qt6-5compat-devel
    - qt6-webengine-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
