name       : systemsettings
version    : 5.92.0
release    : 94
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/systemsettings-5.92.0.tar.xz : 813e189ab51084fa848bc1eeb15ceae698bd758c2b4665804a6100ed082d328e
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
optimize   : lto
builddeps  :
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knotifications-devel
    - kf6-krunner-devel
    - plasma-activities-devel
    - plasma-workspace-devel
rundeps    :
    - flatpak-kcm
    - kf6-kirigami
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rf $installdir/usr/share/doc
