name       : python-torchaudio
version    : 2.2.0
release    : 6
source     :
    - https://github.com/pytorch/audio/archive/refs/tags/v2.2.0.tar.gz : 44de918ba46ee92aa081b91d2095cd980d16a93af8d1aacfcbdb1b5ec161b74b
homepage   : https://pytorch.org/audio
license    : BSD-3-Clause
component  : programming.python
summary    : Datasets, Transforms and Models specific to Computer Vision
description: |
    The torchaudio package consists of popular datasets, model architectures, and common image transformations for computer audio.
clang      : yes
networking : yes
builddeps  :
    - pkgconfig(libavformat)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(tbb)
    - libtorch-devel
    - pytorch
    - rocm-hip
rundeps    :
    - numpy
    - python-pillow
    - python-six
    - python-tqdm
    - pytorch
environment: |
    export MAX_JOBS=%YJOBS%

    export USE_ROCM=1 \
      USE_OPENMP=1

    export ROCM_PATH=/usr
    export HIP_PATH=/usr
    export HIP_CLANG_PATH=/usr/lib64/llvm-rocm/bin
    export HIP_CXX_COMPILER=/usr/bin/hipcc
    export DEVICE_LIB_PATH="/usr/lib64/amdgcn/bitcode"
    export PYTORCH_ROCM_ARCH="%AMDGPUTARGETS%"
    export HIP_CLANG_LAUNCHER=/usr/bin/sccache
setup      : |
    %patch -p1 -i $pkgfiles/cmake.diff
build      : |
    %python3_setup
install    : |
    %python3_install
