name       : freerdp
version    : 3.9.0
release    : 41
source     :
    - https://pub.freerdp.com/releases/freerdp-3.9.0.tar.gz : 2eef25f2b421dbe7b6ca64a96045afe57a4b8c559339baca8cb8528c42518b83
homepage   : https://www.freerdp.com/
license    : Apache-2.0
component  : network.util
summary    : FreeRDP is a free remote desktop protocol client
description: |
    FreeRDP is a free implementation of the Remote Desktop Protocol (RDP).
builddeps  :
    - pkgconfig(SDL2_ttf)
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(cups)
    - pkgconfig(fuse3)
    - pkgconfig(json-c)
    - pkgconfig(libavcodec)
    - pkgconfig(libcjson)
    - pkgconfig(libpcsclite)
    - pkgconfig(libpkcs11-helper-1)
    - pkgconfig(libpulse)
    - pkgconfig(libusbredirhost)
    - pkgconfig(mit-krb5)
    - pkgconfig(sdl2)
    - pkgconfig(wayland-client)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - docbook-xml
clang      : yes
optimize   : thin-lto
setup      : |
    %cmake_ninja \
        -DWITH_BINARY_VERSIONING=ON \
        -DWITH_MANPAGES=ON \
        -DWITH_SSE2=ON \
        -DUWAC_FORCE_STATIC_BUILD=ON # fixme! fix conflicts with freerdp2
build      : |
    %ninja_build
install    : |
    %ninja_install
