name       : ffmpegthumbs
version    : 24.08.3
release    : 85
source     :
    - https://download.kde.org/stable/release-service/24.08.3/src/ffmpegthumbs-24.08.3.tar.xz : 1945360c68e6738828b7130f0d7b5b64ea129edd581bbebf665296e4a9c3cac4
homepage   : https://kde.org/applications/multimedia/org.kde.ffmpegthumbs
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Video thumbnail generator
description: |
    FFMpegThumbs is a video thumbnail generator for KDE file managers.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(libavcodec)
    - pkgconfig(taglib)
    - kf6-kio-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
