name       : python-argcomplete
version    : 3.5.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/source/a/argcomplete/argcomplete-3.5.1.tar.gz : eb1ee355aa2557bd3d0145de7b06b2a45b0ce461e1e7813f5d066039ab4177b4
homepage   : https://github.com/kislyuk/argcomplete
license    : Apache-2.0
component  : programming.python
summary    : Python and tab completion, better together
description: |
    Argcomplete provides easy, extensible command line tab completion of arguments for your Python script.
builddeps  :
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
