name       : python-pyclipper
version    : 1.2.1
release    : 1
source     :
    - https://github.com/fonttools/pyclipper/archive/refs/tags/1.2.1.tar.gz : da6d5858ddaa38c79a684b2389671765003dc6fba015c954c995b09b801a93a0
homepage   : https://pypi.org/project/pyclipper
license    : MIT
component  : programming.python
summary    : Cython wrapper for the C++ translation of the Angus Johnson's Clipper library
description: |
    Pyclipper is a Cython wrapper exposing public functions and classes of the C++ translation of the Angus Johnson’s Clipper library.
builddeps  :
    - pkgconfig(polyclipping)
    - cython
    - python-setuptools-scm-git-archive
    - python-wheel
checkdeps  :
    - pytest-runner
    - pytest-subtests
    - sympy
rundeps    :
    - polyclipping
    - sympy
environment: |
    export SETUPTOOLS_SCM_PRETEND_VERSION=%version%
setup      : |
    sed -i "s/'unittest2', //" setup.py
    sed -i s/unittest2/unittest/ tests/test_pyclipper.py
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
