name       : kscreen
version    : 5.92.0
release    : 91
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kscreen-5.92.0.tar.xz : 3124574331bc3bc78054e21a9745c28213481bd4517c44b0775d5cf2c02a7903
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : KDE Plasma screen management
description: |
    KDE Plasma screen management.
optimize   : lto
builddeps  :
    - pkgconfig(xi)
    - pkgconfig(xcb-atom)
    - pkgconfig(kscreen2)
    - pkgconfig(Qt6Sensors)
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-ki18n-devel
    - kf6-kiconthemes-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
    - kf6-kwindowsystem-devel
    - kf6-kxmlgui-devel
    - layer-shell-qt-devel
    - libplasma-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
