name       : kate
version    : 24.01.90
release    : 78
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/kate-24.01.90.tar.xz : dcd62c462e837d3af42a9cb16dd9b349ba5061d1451c2d36318221e8a0f20790
homepage   : https://apps.kde.org/kate
license    :
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
    - MIT
component  : desktop.kde.core
summary    : KDE advanced text editor
description: Kate is a multi-document, multi-view text editor by KDE. It features stuff like codefolding, syntaxhighlighting, dynamic word wrap, an embedded console, an extensive plugin interface and some prelimentary scripting support. This package also contains kwrite, a lightweight
    editor
optimize   : lto
builddeps  :
    - pkgconfig(libgit2)
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kf6-kuserfeedback-devel
    - kf6-kwallet-devel
    - kf6-syntax-highlighting-devel
    - kf6-ktexteditor-devel
    - kf6-ktextwidgets-devel
    - libplasma-devel
    - plasma-activities-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache

    # remove docs
    rm -rf $installdir/usr/share/doc
