name       : plasma-workspace-wallpapers
version    : 5.92.0
release    : 2
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-workspace-wallpapers-5.92.0.tar.xz : 1682c98ec1c03e209fb79329885dbcdb0e7fc5a38d1be8776ad654b422528cf6
homepage   : https://kde.org/plasma-desktop
license    :
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  : desktop.kde
summary    : Wallpapers for Plasma Workspaces
description: |
    Wallpapers for Plasma Workspaces
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
