name       : plasma-workspace
version    : 5.92.0
release    : 136
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-workspace-5.92.0.tar.xz : bbe200ff10d5dafb274204da5e6e57db2b012364a1abd32f1e1da23b76cd6b94
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
summary    : KDE Plasma workspace
description: This package provides the interface and basic tools for the Plasma workspace.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    # - pkgconfig(dbusmenu-qt6)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libcanberra)
    - pkgconfig(libnm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libqalculate)
    - pkgconfig(libxcrypt)
    - pkgconfig(phonon4qt6)
    - pkgconfig(polkit-qt6-1)
    - pkgconfig(sm)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-image)
    - pkgconfig(xcb-util)
    - pkgconfig(xcursor)
    - pkgconfig(xft)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrender)
    - pkgconfig(xtst)
    - breeze-devel
    - iso-codes
    - kf6-baloo-devel
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kded-devel
    - kf6-kdesu-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kglobalaccel-devel
    - kf6-kguiaddons-devel
    - kf6-kholidays-devel
    - kf6-kiconthemes-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kquickcharts-devel
    - kf6-krunner-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ksvg-devel
    - kf6-ktexteditor-devel
    - kf6-ktextwidgets-devel
    - kf6-kunitconversion-devel
    - kf6-kuserfeedback-devel
    - kf6-kwallet-devel
    - kf6-kxmlgui-devel
    - kf6-networkmanager-qt-devel
    - kf6-prison-devel
    - kf6-sonnet-devel
    - kf6-syntax-highlighting-devel
    - kio-extras-devel
    - kirigami-addons-devel
    - knotifyconfig-devel
    - kpeople-devel
    - kpipewire-devel
    - kscreenlocker-devel
    - ktexteditor-devel
    - kwin-devel
    - layer-shell-qt-devel
    - libkexiv2-devel
    - libkscreen-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
    - plasma-activities-stats-devel
    - plasma-kwayland-devel
    - plasma-wayland-protocols-devel
    - plasma5support-devel
rundeps    :
    - kio-extras
    - kio-fuse
    - kf6-kirigami
    - kf6-kquickcharts
    - mkfontscale
    # TODO
    # maliit-keyboard
    - pipewire
    - vala-panel-appmenu
    - xdg-desktop-portal-kde
    - xdg-user-dirs
    - xdg-utils
    - xprop
    - xrdb
    - xsetroot
patterns   :
    - /usr/lib64/libkdeinit5*.so
    - /usr/lib64/libkrdb.so
replaces   :
    - plasma-workspace-wayland-session
setup      : |
    %apply_patches
    %cmake_kf6 -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/doc
    %qml6_cache

    # SDDM should use a Wayland session with Kwin when we have plasma-workspace installed
    install -Dm00644 $pkgfiles/sddm-wayland.conf $installdir/usr/share/sddm/sddm.conf.d/50_plasma_wayland.conf
