name       : breeze
version    : 5.92.0
release    : 106
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/breeze-5.92.0.tar.xz : 031426b9ad28352c7688487f8ee2a54b4c3cc59478602de7e745bff98ec3cf82
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - GPL-2.0-or-later
    - MIT
component  :
    - desktop.theme
    - ^breeze-cursor-theme : desktop.theme
    - ^breeze-light-cursor-theme : desktop.theme
summary    :
    - Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
    - ^breeze-cursor-theme : Breeze cursor theme
    - ^breeze-light-cursor-theme : Breeze Snow cursor theme
description:
    - Artwork, styles and assets for the Breeze visual style for the Plasma Desktop
    - ^breeze-cursor-theme : Breeze cursor theme
    - ^breeze-light-cursor-theme : Breeze Snow cursor theme
patterns   :
    - ^breeze-cursor-theme :
        - /usr/share/icons/breeze_cursors
        - /usr/share/icons/default/index.theme
    - ^breeze-light-cursor-theme :
        - /usr/share/icons/Breeze_Light
replaces   :
    - ^breeze-light-cursor-theme : breeze-snow-cursor-theme
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt6Quick)
    - pkgconfig(x11)
    - frameworkintegration-devel
    - kcmutils-devel
    - kdecoration-devel
    - kf6-frameworkintegration-devel
    - kf6-kcmutils-devel
    - kf6-kguiaddons-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-kwindowsystem-devel
    - kguiaddons-devel
    - ki18n-devel
    - kirigami2-devel
    - kwindowsystem-devel
clang      : yes
optimize   : lto
rundeps    :
    - devel :
        - breeze-cursor-theme
        - breeze-light-cursor-theme
setup      : |
    %cmake_kf6 -B qt5-build -DBUILD_QT5=ON -DBUILD_QT6=OFF

    %cmake_kf6 -B qt6-build -DBUILD_QT5=OFF -DBUILD_QT6=ON
build      : |
    %ninja_build -C qt5-build
    %ninja_build -C qt6-build
install    : |
    %ninja_install -C qt5-build
    %qml_cache

    %ninja_install -C qt6-build
    %qml6_cache

    # Electron-based applications will segfault if this doesn't exist. Do not remove under any circumstance.
    install -Dm00644 $pkgfiles/index.theme $installdir/usr/share/icons/default/index.theme
