name       : hyprutils
version    : 0.2.4
release    : 3
source     :
    - https://github.com/hyprwm/hyprutils/archive/refs/tags/v0.2.4.tar.gz : ce8455a7bb74e2266910f9a3c1fcbcc9fa4317ca057ba6e8fbf79ec95c8ef699
homepage   : https://github.com/hyprwm/hyprutils
license    : BSD-3-Clause
component  : desktop-hyprland
summary    : Small C++ library for the Hypr* ecosystem.
description: |
    Hyprutils is a small C++ library for utilities used across the Hypr* ecosystem.
builddeps  :
    - pkgconfig(pixman-1)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
