name       : doctl
version    : 1.117.0
release    : 5
source     :
    - https://github.com/digitalocean/doctl/archive/refs/tags/v1.117.0.tar.gz : 2ff734465d45a95a1e31032ea607d05c2582ef28406d7f64142705339a58f3da
homepage   : https://github.com/digitalocean/doctl/
license    : Apache-2.0
component  : network.client
summary    : The official command line interface for the DigitalOcean API.
description: |
    The official command line interface for the DigitalOcean API.
builddeps  :
    - golang
networking : yes
build      : |
    go build \
        -trimpath \
        -buildmode=pie \
        -mod=readonly \
        -ldflags "-linkmode external -extldflags \"${LDFLAGS}\"
        -X github.com/digitalocean/doctl.Major=$(echo $version | cut -d. -f1)
        -X github.com/digitalocean/doctl.Minor=$(echo $version | cut -d. -f2)
        -X github.com/digitalocean/doctl.Patch=$(echo $version | cut -d. -f3)
        -X github.com/digitalocean/doctl.Label=release
        " \
        ./cmd/...
    mkdir completions
    ./doctl completion bash > completions/doctl
    ./doctl completion fish > completions/doctl.fish
    ./doctl completion zsh > completions/_doctl
install    : |
    install -Dm00755 doctl $installdir/usr/bin/doctl
    install -Dm00755 completions/doctl $installdir/usr/share/bash-completions/doctl
    install -Dm00755 completions/doctl.fish $installdir/usr/share/fish/vendor_completions.d/doctl.fish
    install -Dm00755 completions/_doctl $installdir/usr/share/zsh/site-functions/_doctl

