name       : knotifications
version    : 5.115.0
release    : 74
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/knotifications-5.115.0.tar.xz : fb8271ffbbbb570949326eb28ccfe3fe36d97be4b07172b8992a546791570642
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.library
summary    : Desktop notifications.
description: |
    Desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(dbusmenu-qt5)
    - pkgconfig(libcanberra)
    - kconfig-devel
    - kcoreaddons-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
