name       : lua
version    : 5.4.6
release    : 7
source     :
    - https://www.lua.org/ftp/lua-5.4.6.tar.gz : 7d5ea1b9cb6aa0b59ca3dde1c6adcb57ef83a1ba8e5432c0ecd06bf439b3ad88
license    : MIT
homepage   : https://www.lua.org/
component  : programming
summary    : Lightweight programming language
description: |
    Lua is a powerful light-weight programming language designed for extending applications. It is also frequently used as a general-purpose, stand-alone language. Lua is implemented as a small library of C functions, written in ANSI C, and compiles unmodified in all known platforms. The implementation goals are simplicity, efficiency, portability, and low embedding cost. The result is a fast language engine with small footprint, making it ideal in embedded systems too.
patterns   :
    - devel : [/usr/bin]
setup      : |
    unset LD_AS_NEEDED
    %patch -p1 -i $pkgfiles/0001-Use-shared-libraries-and-proper-prefix.patch
build      : |
    unset LD_AS_NEEDED
    %make linux
install    : |
    unset LD_AS_NEEDED
    %make_install INSTALL_TOP=$installdir/usr TO_LIB="liblua.so liblua.so.5.4 liblua.so.${version}" INSTALL_DATA="cp -d" INSTALL_MAN=$installdir/usr/share/man/man1
    install -Dm00644 $pkgfiles/lua-5.4.pc $installdir/usr/lib/pkgconfig/lua-5.4.pc
    ln -s lua-5.4.pc $installdir/usr/lib/pkgconfig/lua.pc
