name       : gtest
version    : 1.14.0
release    : 8
source     :
    - https://github.com/google/googletest/archive/refs/tags/v1.14.0.tar.gz : 8ad598c73ad796e0d8280b082cebd82a630d73e73cd3c70057938a6501bba5d7
homepage   : https://google.github.io/googletest/
license    : BSD-3-Clause
libsplit   : no
component  : programming.tools
summary    : Google's C++ test framework
description: |
    GoogleTest is Google’s C++ testing and mocking framework.
setup      : |
    sed -i 's/DESTINATION lib/DESTINATION lib64/' google{mock,test}/CMakeLists.txt

    # Set the version correctly
    sed -e "s/set(GOOGLETEST_VERSION .*)/set(GOOGLETEST_VERSION %version%)/" -i CMakeLists.txt

    %cmake -DBUILD_SHARED_LIBS=ON \
           -DPYTHON_EXECUTABLE=python3 \
           -Dgtest_build_tests=ON
build      : |
    %make
install    : |
    %make_install
check      : |
    ctest
patterns   :
    - /*
