name       : haruna
version    : 1.2.1
release    : 21
source     :
    - https://download.kde.org/stable/haruna/1.2.1/haruna-1.2.1.tar.xz : eb01261a3498c6e25c28064e6ccea37aeb38cd8aa5006f02c92760b124c362fb
homepage   : https://invent.kde.org/multimedia/haruna/
license    :
    - BSD-3-Clause
    - CC-BY-4.0
    - CC-BY-SA-4.0
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : multimedia.audio
summary    : Video player built with Qt/QML on top of libmpv.
description: |
    Video player built with Qt/QML on top of libmpv.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(libavformat)
    - pkgconfig(mpv)
    - breeze-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - mpvqt-devel
rundeps    :
    - breeze
    - breeze-icons
    - kf6-kirigami
    - kf6-qqc2-desktop-style
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-Force-opening-remote-files-with-kio-fuse.patch
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rfv $installdir/usr/share/doc
