name       : libopenshot
version    : 0.3.3
release    : 38
source     :
    - https://github.com/OpenShot/libopenshot/archive/refs/tags/v0.3.3.tar.gz : 591b74651ddf59f83d69a592d84bbabbe7290293092a87be9c2993d5ce9a1638
homepage   : https://www.openshot.org/
license    : LGPL-3.0-or-later
component  : multimedia.library
summary    : A high quality, open-source video editing, animation, and playback library for C++, Python and Ruby
description: |
    libopenshot is an open-source, cross-platform C++ library dedicated to delivering high quality video editing, animation, and playback solutions to the world. This is the same library which powers OpenShot Video Editor (version 2.0+) and it could power your next video editing application!
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Svg)
    - pkgconfig(alsa)
    - pkgconfig(cppzmq)
    - pkgconfig(gl)
    - pkgconfig(jsoncpp)
    - pkgconfig(libavcodec)
    - pkgconfig(python3)
    - pkgconfig(ruby-3.2)
    - pkgconfig(x264)
    - doxygen
    - libopenshot-audio-devel
    - swig
checkdeps  :
    - pkgconfig(catch2)
setup      : |
    # Sometimes build fails with ruby enabled.
    # Use -DENABLE_RUBY=OFF to disable it and reenable at a later date.
    %cmake_ninja -DUSE_SYSTEM_JSONCPP=ON -DLIB_SUFFIX=%LIBSUFFIX%
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check || :
