name       : plasma5support
version    : 5.92.0
release    : 1
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma5support-5.92.0.tar.xz : 77fd65179268738a31ebfa0d9f7289197bf3970e7d0ec213032950420f998e7f
homepage   : https://invent.kde.org/plasma/plasma5support
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.libraries
summary    : Support components for porting from KF5/Qt5 to KF6/Qt6
description: |
    Support components for porting from KF5/Qt5 to KF6/Qt6
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6Gui)
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Sql)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Widgets)
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
