name       : digikam
version    : 8.3.0
release    : 48
source     :
    - https://download.kde.org/stable/digikam/8.3.0/digiKam-8.3.0-1.tar.xz : 05b145ff7f2f2005fa21bc579c152ab23c8191b678ff2944c8f0406d6b9de6d8
homepage   : https://www.digikam.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.graphics
libsplit   : no
summary    : Advanced digital photo management application
description: |
    digiKam is an advanced digital photo management application for KDE, which makes importing and organizing digital photos a 'snap'.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(KF6CalendarCore)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6NetworkAuth)
    - pkgconfig(Qt6StateMachine)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WebEngineCore)
    - pkgconfig(eigen3)
    - pkgconfig(exiv2)
    - pkgconfig(jasper)
    - pkgconfig(lcms2)
    - pkgconfig(lensfun)
    - pkgconfig(libavformat)
    - pkgconfig(libgphoto2)
    - pkgconfig(libheif)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxslt)
    - pkgconfig(opencv4)
    # - pkgconfig(xext)
    - akonadi-contacts-devel
    - breeze-devel
    - breeze-icons-devel
    - kf6-kcontacts-devel
    - kf6-kfilemetadata-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-sonnet-devel
    - kf6-threadweaver-devel
    - libboost-devel
    - libksane-devel
    # - marble-devel # Not Qt6 yet
rundeps    :
    - breeze
    - breeze-icons
    - perl-image-exiftool
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %patch -p1 -i $pkgfiles/0001-KF6-dependency-fixes.patch

    %cmake_ninja \
        -DBUILD_TESTING=OFF \
        -DBUILD_WITH_QT6=ON \
        -DENABLE_KFILEMETADATASUPPORT=ON \
        -DENABLE_AKONADICONTACTSUPPORT=ON \
        -DENABLE_APPSTYLES=ON \
        -DENABLE_QWEBENGINE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Due to SC limitation
    rm -v $installdir/usr/share/metainfo/org.kde.showfoto.appdata.xml
