# NOTE TO PACKAGERS: rebuild this after every Qt stack upgrade due to using private headers!
name       : qadwaitadecorations
version    : 0.1.4
release    : 1
source     :
    - https://github.com/FedoraQt/QAdwaitaDecorations/archive/refs/tags/0.1.4.tar.gz : e2b813c55e8ed6679eaa4a201f9ed6a2c8bc320260fb45dbd77c7724fd095e4e
homepage   : https://github.com/FedoraQt/QAdwaitaDecorations
license    : LGPL-2.1-or-later
component  : desktop.theme
summary    : Qt decoration plugin implementing Adwaita-like client-side decorations
description: |
    QAdwaitaDecorations - Qt decoration plugin implementing Adwaita-like client-side decorations (currently Qt5 and Qt6).
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt6WaylandClient)
setup      : |
    mkdir build-qt6
    pushd build-qt6
        %cmake_ninja -DUSE_QT6=true ../
    popd
    mkdir build-qt5
    pushd build-qt5
        # NOTE TO PACKAGERS: HAS_QT6_SUPPORT means we carry a backported patch from qt6 in qt5-wayland.
        %cmake_ninja -DHAS_QT6_SUPPORT=true ../
    popd
build      : |
    pushd build-qt6
        %ninja_build
    popd
    pushd build-qt5
        %ninja_build
    popd
install    : |
    pushd build-qt6
        %ninja_install
    popd
    pushd build-qt5
        %ninja_install
    popd
