name       : kpipewire
version    : 5.92.0
release    : 10
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kpipewire-5.92.0.tar.xz : 89537ab244584e76dda97857a548b5f6d143383a496c5c4068a0c18b5930483f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Components relating to pipewire use in Plasma
description: |
    Components relating to pipewire use in Plasma
patterns   :
    - /usr/lib64/libKPipeWire*.so
    - /usr/lib64/libKPipeWireRecord*.so
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(gbm)
    - pkgconfig(libavformat)
    - pkgconfig(libdrm)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libva)
    - extra-cmake-modules
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    - plasma-kwayland-devel
    - plasma-wayland-protocols-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
