name       : print-manager
version    : 5.92.0
release    : 77
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/print-manager-5.92.0.tar.xz : 32113b93eb29f3a324903bffa8fe8b64acd34a7c3f2ae5d6fb5300770a4b0345
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(Qt6Core5Compat)
    - cups-devel
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - kirigami-addons-devel
    - libplasma-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
