name       : shotcut
version    : 24.10.29
release    : 41
source     :
    - https://github.com/mltframework/shotcut/archive/refs/tags/v24.10.29.tar.gz : 8635486cfb0e8e0d50e264e97a3ab4c57b2901742b188aed3ee91ac0371b3250
homepage   : https://www.shotcut.org/
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A free, open source, and cross-platform video editor
description: |
    Shotcut is a free and open-source cross-platform video editing application for FreeBSD, Linux, macOS and Windows. It supports video, audio, and image formats via FFmpeg, and uses a timeline for non-linear video editing of multiple tracks that may be composed of various file formats. Scrubbing and transport control are assisted by OpenGL GPU-based processing and a number of video and audio filters are available.
libsplit   : no
builddeps  :
    - pkgconfig(Qt6Charts)
    - pkgconfig(Qt6Help)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6WebSockets)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(mlt-framework-7)
    - pkgconfig(x11)
rundeps    :
    - frei0r
    - sdl2
    - swh-plugins
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    # Disable new version check
    export CXXFLAGS+=" -DSHOTCUT_NOUPGRADE"

    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSHOTCUT_VERSION=%version%
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
