name       : cppcheck
version    : 2.16.0
release    : 29
source     :
    - https://github.com/danmar/cppcheck/archive/refs/tags/2.16.0.tar.gz : f1a97c8cef5ee9d0abb57e9244549d4fe18d4ecac80cf82e250d1fc5f38b1501
homepage   : https://cppcheck.sourceforge.io/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : Static source code analysis tool for C and C++ code
description: |
    Cppcheck is a static analysis tool for C/C++ code. It provides unique code analysis to detect bugs and focuses on detecting undefined behaviour and dangerous coding constructs. The goal is to detect only real errors in the code (i.e. have very few false positives).
builddeps  :
    - pcre2
setup      : |
    %cmake_ninja . -DBUILD_TESTS=ON -DHAVE_RULES=OFF -DUSE_MATCHCOMPILER=On
build      : |
    %ninja_build
install    : |
    %ninja_install
