name       : kf6-kfilemetadata
version    : 6.8.0
release    : 14
source     :
    - https://download.kde.org/stable/frameworks/6.8/kfilemetadata-6.8.0.tar.xz : 50466b3699bbe3017edb0c3cb09463a57e2dd3b66d60f5f610d9ee3a21e34894
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Simple library for extracting the text and metadata
description: |
    Simple library for extracting the text and metadata
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(libattr)
    - pkgconfig(libavformat)
    - pkgconfig(poppler-qt6)
    - pkgconfig(taglib)
    - ebook-tools-devel
    - kdegraphics-mobipocket-devel
    - kf6-karchive-devel
    - kf6-kcodecs-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-ki18n-devel
    # TODO add catdoc, libappimage
rundeps    :
    - devel :
        - qt6-base-devel
clang      : yes
optimize   : thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
