name       : linux-firmware
version    : '20241110'
release    : 83
source     :
    - git|https://gitlab.com/kernel-firmware/linux-firmware.git : 20241110
license    :
    - GPL-2.0-or-later
    - Distributable
component  : kernel
homepage   : https://git.kernel.org/?p=linux/kernel/git/firmware/linux-firmware.git;a=summary
summary    :
    - Firmware required for many devices
    - nvidia : Firmware required for many devices, Nvidia GSP firmware (unused)
description:
    - Free and non-free firmware required for enablement of many devices and hardware
    - nvidia : Firmware required for many devices, Nvidia GSP firmware (unused)
strip      : no
debug      : no
networking : yes
builddeps  :
    - rdfind
rundeps    :
    - intel-microcode
# setup      : |
#     git config --global user.email "solus@getsol.us"
#     git config --global user.name "Solus"

#     # Fixes an issue with vp9 decoding on certain AMD hardware
#     git cherry-pick -n 977332782302476e1c863b09b840f463d0378807
install    : |
    %make install-zst DESTDIR="$installdir" FIRMWAREDIR="/usr/lib64/firmware"

    # Remove blacklisted
    for i in airoha carl9170fw netronome liquidio powervr qed; do
        rm -rvf $installdir/usr/lib64/firmware/$i
    done

    # Exit if there are any absolute symlinks anywhere since those will mess things up
    pushd $installdir/
    ! find . -type l -lname '/*' -print | grep .
    popd

    # Usr-merge
    install -dm00755 $installdir/lib64
    pushd $installdir/usr
    dir_list=()
    while IFS=  read -r -d $'\0'; do
        dir_list+=("$REPLY")
    done < <(find lib64 -type d -print0)
    for file in "${dir_list[@]}"; do
        install -dm00755 "$installdir/$file"
    done

    file_list=()
    while IFS=  read -r -d $'\0'; do
        file_list+=("$REPLY")
    done < <(find lib64 -type f -print0)
    for file in "${file_list[@]}"; do
        ln -srv "$installdir/usr/$file" "$installdir/$file"
    done

    link_list=()
    while IFS=  read -r -d $'\0'; do
        link_list+=("$REPLY")
    done < <(find lib64 -type l -print0)
    for file in "${link_list[@]}"; do
        link=$(readlink "$file")
        ln -sv "$link" "$installdir/$file"
    done
    popd

    # Stick docs in
    install -dDm00755 $installdir/usr/share/doc/${package}
    install -m00644 LICENSE* $installdir/usr/share/doc/${package}/.
    install -m00644 LICENCE* $installdir/usr/share/doc/${package}/.
patterns   :
    - nvidia :
        - /lib64/firmware/nvidia/ad*/gsp
        - /lib64/firmware/nvidia/ga*/gsp
        - /lib64/firmware/nvidia/tu*/gsp
        - /usr/lib64/firmware/nvidia/ad*/gsp
        - /usr/lib64/firmware/nvidia/ga*/gsp
        - /usr/lib64/firmware/nvidia/tu*/gsp
