name       : milou
version    : 5.92.0
release    : 91
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/milou-5.92.0.tar.xz : 91a6af4612b7031de7e839ab5e3697105d575ea00e7b83e2c7c43aba43a58d41
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : A dedicated search application built on top of Baloo
description: |
    A dedicated search application built on top of Baloo.
builddeps  :
    - kf6-kdeclarative-devel
    - kf6-ki18n-devel
    - kf6-kitemmodels-devel
    - kf6-kpackage-devel
    - kf6-krunner-devel
    - kf6-ksvg-devel
    - kf6-kwindowsystem-devel
    - libplasma-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
