name       : ocean-sound-theme
version    : 5.92.0
release    : 1
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/ocean-sound-theme-5.92.0.tar.xz : 8809fc04b539cac514b8aa9dbf1a91da1b828bfc60e6c12d401c355848d3f87f
homepage   : https://kde.org/plasma-desktop
license    :
    - BSD-2-Clause
    - CC-BY-SA-4.0
    - CC0-1.0
component  : desktop
summary    : Ocean Sound Theme for Plasma
description: |
    Ocean Sound Theme for Plasma
builddeps  :
    - pkgconfig(Qt6Core)
    - extra-cmake-modules
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
