name       : gwenview
version    : 24.01.90
release    : 83
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/gwenview-24.01.90.tar.xz : 7bb6e2654a10a9f3c37f5f29dc527ad138d52c49bbecdb3bc40772ba994cbc39
homepage   : https://kde.org/applications/graphics/org.kde.gwenview
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : Fast and easy to use image viewer by KDE
description: |
    Gwenview is able to load and save to a variety of image formats supported by KDE applications, such as PNG, JPEG, and even the Gimp's XCF! Gwenview also sports a beautiful thumbnail toolbar when viewing images in fullscreen. Gwenview's simple interface doesn't get in the way and lets you view your images quickly and easily.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(exiv2)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(phonon4qt6)
    - pkgconfig(x11)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - kcolorpicker-devel
    - kf6-baloo-devel
    - kf6-kdoctools-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kitemmodels-devel
    - kf6-knotifications-devel
    - kf6-kparts-devel
    - kf6-purpose-devel
    - kimageannotator-devel
    - libkdcraw-devel
    - plasma-activities-devel
rundeps    :
    - kimageformats
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove doc
    rm -rf $installdir/usr/share/doc
