name       : libplasma
version    : 5.92.0
release    : 1
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/libplasma-5.92.0.tar.xz : 738dcf328e19b02dc25b5ddada675b5240d944302f0c5110126f33187879b9d0
homepage   : https://kde.org/plasma-desktop/
license    :
    - BSD-3-Clause
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Plasma library and runtime components
description: |
    Plasma library and runtime components
builddeps:
    - pkgconfig(Qt6QuickControls2)
    - pkgconfig(Qt6Svg)
    - kf6-karchive-devel
    - kf6-kcmutils-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - kf6-ksvg-devel
    - plasma-activities-devel
    - plasma-kwayland-devel
    - plasma-wayland-protocols-devel
    - qt6-wayland-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
