name       : sddm-kcm
version    : 5.92.0
release    : 87
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/sddm-kcm-5.92.0.tar.xz : cafef607edc7746a13b6a9fd21a4af0162035dc8cdfa6d03837c6f9847a5c967
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Config module for SDDM
description: |
    Hosts the KCM module for SDDM. This module allows for configuring SDDM in Plasma System Settings.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Quick)
    - pkgconfig(xcb-cursor)
    - pkgconfig(xcursor)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdeclarative-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
