name       : kglobalacceld
version    : 5.92.0
release    : 1
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kglobalacceld-5.92.0.tar.xz : feb35c9b4a06bf9079a00d0d180ad170e69133e6a66670c2ce165cd8663224b4
homepage   : https://kde.org/plasma-desktop/
license    :
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - LGPL-3.0-only
component  : desktop.library
summary    : Daemon providing Global Keyboard Shortcut (Accelerator) functionality
description: |
    Daemon providing Global Keyboard Shortcut (Accelerator) functionality
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(Qt6DBus)
    - pkgconfig(Qt6Gui)
    - pkgconfig(Qt6Widgets)
    - pkgconfig(xcb)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-record)
    - pkgconfig(xcb-xkb)
    - pkgconfig(xcb-xtest)
    - pkgconfig(xkbcommon)
    - extra-cmake-modules
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kwindowsystem-devel
    - kf6-kglobalaccel-devel
    - kf6-kservice-devel
    - kf6-kio-devel
    - kf6-kjobwidgets-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
