name       : plasma-sdk
version    : 5.92.0
release    : 75
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-sdk-5.92.0.tar.xz : 105060b3d72b35338eceecca0b974411ebba138b1d487554d2284a9ee6d783cb
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde
summary    : Applications useful for Plasma Development
description: |
    Applications useful for Plasma Development.
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - kf6-karchive-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-kpackage-devel
    - kf6-kparts-devel
    - kf6-ksvg-devel
    - kf6-ktexteditor-devel
    - kf6-kxmlgui-devel
    - kf6-syntax-highlighting-devel
    - libplasma-devel
    - plasma5support-devel
setup      : |
    rm -fr $workdir/po/nl/docs/plasma-sdk
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
