name       : alsa-lib
version    : 1.2.13
release    : 39
source     :
    - https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.13.tar.bz2 : 8c4ff37553cbe89618e187e4c779f71a9bb2a8b27b91f87ed40987cc9233d8f6
    - https://www.alsa-project.org/files/pub/lib/alsa-topology-conf-1.2.5.1.tar.bz2 : f7c5bae1545abcd73824bc97f4e72c340e11abea188ba0f1c06f5e0ad776b179
    - https://www.alsa-project.org/files/pub/lib/alsa-ucm-conf-1.2.13.tar.bz2 : 4483b6e3983cca08fd326a73fbae449b5036e444fb1a07c0dee74b504b7ab5af
homepage   : https://www.alsa-project.org
license    : LGPL-2.1-or-later
component  : multimedia.audio
summary    : The ALSA Sound Interface
description: |
    The ALSA Library package contains the ALSA library used by programs (including ALSA Utilities) requiring access to the ALSA sound interface.
patterns   :
    - devel : /usr/share/aclocal/alsa.m4
emul32     : yes
setup      : |
    %patch -p1 -i $pkgfiles/0001-Support-a-stateless-configuration.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/asound.conf $installdir/usr/share/defaults/alsa/asound.conf
    install -dm00755 $installdir/usr/share/alsa/{ucm,ucm2,topology}
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        pushd $installdir/usr/share/alsa/
        tar xvjf $sources/alsa-topology-conf-*.tar.bz2 --strip-components=1
        tar xvjf $sources/alsa-ucm-conf-*.tar.bz2 --strip-components=1
        find -path "*.md" -prune -exec rm -r '{}' \; \
            -or -name "LICENSE" -prune -exec rm -r '{}' \;
        popd
    fi
check      : |
    # Fails on test/lsb so just ignore
    %make check || :
