name       : kjsembed
version    : 5.115.0
release    : 71
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/portingAids/kjsembed-5.115.0.tar.xz : f6aeac1dcc7e1ce4219ef3a0a8a22c5eb2ab377a9587d5d9fa94b625653e3151
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.java
summary    : Binding Javascript object to QObjects
description: |
    KSJEmbed provides a method of binding JavaScript objects to QObjects, so you can script your applications.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - kdoctools-devel
    - ki18n-devel
    - kjs-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
