name       : libsepol
version    : '3.7'
release    : 3
source     :
    - https://github.com/SELinuxProject/selinux/releases/download/3.7/libsepol-3.7.tar.gz : cd741e25244e7ef6cd934d633614131a266c3eaeab33d8bfa45e8a93b45cc901
homepage   : https://selinuxproject.org/
license    : LGPL-2.1
component  : security.library
summary    : SELinux Policy Library
patterns   :
    - devel : /usr/bin
description: |
    libsepol from SELinux project
build      : |
    %make SHLIBDIR=%libdir% LIBDIR=%libdir%
install    : |
    %make_install SHLIBDIR=%libdir% LIBDIR=%libdir%
