name       : python-spyder-kernels
version    : 3.0.1
release    : 30
source     :
    - https://github.com/spyder-ide/spyder-kernels/archive/refs/tags/v3.0.1.tar.gz : 1c2ee8d1ba33aabaf62104f32f634bf094582449a73917043f5a86cbab1c31d3
homepage   : https://github.com/spyder-ide/spyder-kernels
license    : MIT
component  : programming.ide
summary    : Jupyter Kernels for the Spyder console
description: |
    Package that provides Jupyter kernels for use with the consoles of Spyder, the Scientific Python Development Environment. These kernels can launched either through Spyder itself or in an independent Python session, and allow for interactive or file-based execution of Python code inside Spyder.
rundeps    :
    - python-cloudpickle
    - python-ipykernel
    - python-wurlitzer
build      : |
    %python3_setup
install    : |
    %python3_install
