name       : mgba
version    : 0.10.3
release    : 57
source     :
    - https://github.com/mgba-emu/mgba/archive/refs/tags/0.10.3.tar.gz : be2cda7de3da8819fdab0c659c5cd4c4b8ca89d9ecddeeeef522db6d31a64143
homepage   : https://mgba.io/
license    : MPL-2.0
component  : games.emulator
summary    : Game Boy Advance emulator written in C
description: mGBA is a new Game Boy Advance emulator written in C.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(epoxy)
    - pkgconfig(libavcodec)
    - pkgconfig(libedit)
    - pkgconfig(libelf)
    - pkgconfig(libpng)
    - pkgconfig(libzip)
    - pkgconfig(lua-5.4)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - desktop-file-utils
clang      : yes
setup      : |
    %patch -p1 -i $pkgfiles/ftbfs-gcc-14.patch

    %cmake_ninja -DBUILD_LTO=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Install appstream metainfo
    install -Dm00644 $pkgfiles/io.mgba.mGBA.appdata.xml -t $installdir/usr/share/metainfo/
