name       : powerdevil
version    : 5.92.0
release    : 98
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/powerdevil-5.92.0.tar.xz : ff7d88fd0af4505e9fcd0ad40560fb5ff21ae07bb25f4e1f14a05f816b075941
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Manages the power settings of KDE Plasma
description: |
    Manages the power settings of KDE Plasma.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(ddcutil)
    - pkgconfig(libcap)
    - pkgconfig(libnm)
    - pkgconfig(libudev)
    - pkgconfig(xcb-util)
    - bluez-qt-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kconfig-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-ki18n-devel
    - kf6-kidletime-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-kitemmodels-devel
    - kf6-knotifications-devel
    - kf6-kxmlgui-devel
    - kf6-solid-devel
    - layer-shell-qt-devel
    - libkscreen-devel
    - plasma-activities-devel
    - plasma-workspace-devel
rundeps    :
    - power-profiles-daemon
    - upower
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6 -DHAVE_DDCUTIL=On
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rfv $installdir/usr/share/doc
