name       : kidletime
version    : 5.115.0
release    : 74
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kidletime-5.115.0.tar.xz : 9d8029aa6a740dbcdee6988987d097538f369ce7b6f3dee09d502aa29737ae56
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-only
    - MIT
component  : programming.library
summary    : Reporting of idle time of user and system
description: |
    Reporting of idle time of user and system
optimize   : lto
builddeps  :
    - pkgconfig(Qt5DBus)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WaylandClient)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xscrnsaver)
    - extra-cmake-modules
    - plasma-wayland-protocols-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
