name       : plasma-activities
version    : 5.92.0
release    : 1
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-activities-5.92.0.tar.xz : 2ac1e844f8e840a8b77e3323c4badcf8ed5997633d6cc12812d157bb50fe77c3
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-only
    - MIT
component  : programming.library
summary    : Core components for the KDE Activity concept
description: |
    Plasma Activities provides the infrastructure needed to manage a user's activites, allowing them to switch between tasks, and for applications to update their state to match the user's current activity. This includes a daemon, a library for interacting with that daemon, and plugins for integration with other frameworks.
optimize   : lto
builddeps  :
    - pkgconfig(Qt6Quick)
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kwindowsystem-devel
    - libboost-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
