name       : yakuake
version    : 24.01.90
release    : 57
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/yakuake-24.01.90.tar.xz : 4873a54c661085758d5f6fa8c96164cbda71f11aadae164082f5a3061161167b
homepage   : https://kde.org/applications/system/org.kde.yakuake
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6Widgets)
    - pkgconfig(x11)
    - kf6-karchive-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-knewstuff-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kstatusnotifieritem-devel
    - kwayland-devel
rundeps    :
    - konsole
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
