name       : hypridle
version    : 0.1.5
release    : 2
source     :
    - https://github.com/hyprwm/hypridle/archive/refs/tags/v0.1.5.tar.gz : 174d4b4706ec5c79e6d80a7cc3b297b5564c923f60f408c1638b55424a998a4b
homepage   : https://github.com/hyprwm/hypridle
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : Hyprland's idle daemon.
description: |
    Hyprland's idle daemon.
builddeps  :
    - pkgconfig(hyprlang)
    - pkgconfig(hyprutils)
    - pkgconfig(sdbus-c++)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
