name       : xdg-desktop-portal-kde
version    : 5.92.0
release    : 79
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/xdg-desktop-portal-kde-5.92.0.tar.xz : cc013353880bff3f583d80427a18539bd76dac06a1359b36ba0546cf7e1205c8
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-or-later
component  : desktop.kde
summary    : Qt/KDE for xdg-desktop-portal
description: |
    A backend implementation for xdg-desktop-portal that is using Qt/KDE.
builddeps  :
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(epoxy)
    - pkgconfig(dri)
    - pkgconfig(xkbcommon)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - cups-devel
    - kf6-kdeclarative-devel
    - kf6-kglobalaccel-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kstatusnotifieritem-devel
    - libplasma-devel
    - plasma-kwayland-devel
    - plasma-wayland-protocols-devel
rundeps    :
    - xdg-desktop-portal
    # Needed so that GTK flatpaks respect system settings
    - xdg-desktop-portal-gtk
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
