name       : gstreamer-1.0-libav
version    : 1.24.9
release    : 42
source     :
    - https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.24.9.tar.xz : 32682e9ae508ee01f4fb134b3a520081e2ac007220997577624b1d16171d456c
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gstreamer.freedesktop.org/
summary    : GStreamer libav based plugin
description: |
    GStreamer libav based plugin providing H264, AVI support, amongst others
builddeps  :
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(libavcodec)
setup      : |
    %meson_configure -D package-name="GStreamer Libav Plugins ${version} Solus" \
        -D package-origin="https://getsol.us" 
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
