name       : syntax-highlighting
version    : 5.115.0
release    : 73
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/syntax-highlighting-5.115.0.tar.xz : 0622a719ac243023b87a1592291c55c66ac9c6e79ab7be04fbb68ed2d3f2de0a
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
