name       : telegram
version    : 5.6.3
release    : 220
source     :
    - https://github.com/telegramdesktop/tdesktop/releases/download/v5.6.3/tdesktop-5.6.3-full.tar.gz : e32628184aa571f1051e1f8ac75a67455a07c1753a3be47bfb013994c941db15
    - git|https://github.com/desktop-app/tg_owt.git : 6c6fced78f905d58fc96c7508aff62d9da34171e
homepage   : https://desktop.telegram.org/
license    : GPL-3.0-or-later
component  : network.im
summary    : Telegram Desktop messaging app
description: |
    Telegram is a messaging app with a focus on speed and security, it's super fast, simple and free.
optimize   :
    - function-sections
    - icf-safe
    - thin-lto
builddeps  :
    # - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Svg)
    - pkgconfig(Qt6WaylandClient)
    - pkgconfig(absl_base)
    - pkgconfig(ada)
    - pkgconfig(alsa)
    - pkgconfig(epoxy)
    - pkgconfig(fmt)
    - pkgconfig(glibmm-2.68)
    - pkgconfig(hunspell)
    - pkgconfig(jemalloc)
    - pkgconfig(libavcodec)
    # - pkgconfig(libavif)
    # - pkgconfig(libevent)
    - pkgconfig(libjpeg)
    - pkgconfig(liblz4)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libpulse)
    - pkgconfig(libxxhash)
    # TODO Fix minizip-ng compat
    # - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(openh264)
    - pkgconfig(opus)
    - pkgconfig(protobuf) # For the bundles cdl3 library.
    - pkgconfig(rnnoise)
    - pkgconfig(vpx)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
    - gobject-introspection
    - kf6-kcoreaddons-devel
    # - kf6-kimageformats
    - libboost-devel
    - libdispatch-devel
    # - plasma-wayland-protocols
    # - yasm
rundeps    :
    - qt6-imageformats
clang      : yes
setup      : |
    cp -r $sources/tg_owt.git tg_owt
    pushd tg_owt
        %cmake_ninja
        %ninja_build
    popd

    # Building with -O2 and any variant of LTO seems to cause segfaults during notifications. -O2 is the default for RelWithDebInfo so
    # we need to set the cmake build to None and add the flags manually. It's really weird that -O3 works fine and -O2 doesn't...
    export CXXFLAGS="$CXXFLAGS -O3 -DNDEBUG"

    # Force build against minizip-ng
    # sed -i "s|minizip<2.0.0|minizip|" cmake/external/minizip/CMakeLists.txt
    # pushd Telegram/lib_base
    # %patch -p1 -i $pkgfiles/0001-Fix-build-with-minizip-ng.patch
    # popd

    %cmake_ninja \
        -DCMAKE_BUILD_TYPE=None \
        -DDESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
        -DTDESKTOP_API_HASH=8562eb11c58f218ac08ee12c32e07ece \
        -DTDESKTOP_API_ID=1080918 \
        -Dtg_owt_DIR=$workdir/tg_owt/solusBuildDir
build      : |
    %ninja_build
install    : |
    %ninja_install
# 1515
