name       : aquamarine
version    : 0.4.4
release    : 3
source     :
    - https://github.com/hyprwm/aquamarine/archive/refs/tags/v0.4.4.tar.gz : 2ac672bce27ac8a2f2d236582d49a2b6bbe243e9a7a5d06881e636607e897110
homepage   : https://github.com/hyprwm/aquamarine
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : A very light linux rendering backend library
description: |
    Aquamarine is a very light linux rendering backend library. It provides basic abstractions for an application to render on a Wayland session (in a window) or a native DRM session. It is agnostic of the rendering API (Vulkan/OpenGL) and designed to be lightweight, performant, and minimal. Aquamarine provides no bindings for other languages. It is C++-only.
builddeps  :
    - pkgconfig(gbm)
    - pkgconfig(hwdata)
    - pkgconfig(hyprutils)
    - pkgconfig(hyprwayland-scanner)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libseat)
    - pkgconfig(libudev)
    - pkgconfig(pixman-1)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
