name       : gst-rtsp-server
version    : 1.24.9
release    : 21
source     :
    - https://gstreamer.freedesktop.org/src/gst-rtsp-server/gst-rtsp-server-1.24.9.tar.xz : 299c9aafac3c91bbebe4cd481ed4e4ade8cb2b0677097bc4a8dcf6d4364c9804
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : multimedia.gstreamer
homepage   : https://gstreamer.freedesktop.org
summary    : GStreamer RTSP server library
description: |
    GStreamer's RTSP server (gst-rtsp-server) is a featureful and easy-to-use library that allows applications to implement a complete RTSP server with just a couple of lines of code.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
setup      : |
    %meson_configure \
        -Dpackage-name="GStreamer ${version} Solus" \
        -Dpackage-origin="https://getsol.us"
build      : |
    %ninja_build
install    : |
    %ninja_install
