name       : hyprland
version    : 0.45.0
release    : 3
source     :
    - https://github.com/hyprwm/Hyprland/releases/download/v0.45.0/source-v0.45.0.tar.gz : 9690b5c0c10fdc277ea7988a28318941dde854260ede4339634dbf2bba8192a3
homepage   : https://hyprland.org/
license    : BSD-3-Clause
component  : desktop.hyprland
summary    : Hyprland is a 100% independent, dynamic tiling Wayland compositor that doesn't sacrifice on its looks.
description: |
    Hyprland is a 100% independent, dynamic tiling Wayland compositor that doesn't sacrifice on its looks. It provides the latest Wayland features, is highly customizable, has all the eyecandy, the most powerful plugins, easy IPC, much more QoL stuff than other compositors and more...
builddeps  :
    - pkgconfig(aquamarine)
    - pkgconfig(cairo)
    - pkgconfig(gbm)
    - pkgconfig(gio-2.0)
    - pkgconfig(hwdata)
    - pkgconfig(hyprcursor)
    - pkgconfig(hyprland-protocols)
    - pkgconfig(hyprlang)
    - pkgconfig(hyprutils)
    - pkgconfig(hyprwayland-scanner)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(libliftoff)
    - pkgconfig(libseat)
    - pkgconfig(libudev)
    - pkgconfig(pango)
    - pkgconfig(pangocairo)
    - pkgconfig(pixman-1)
    - pkgconfig(tomlplusplus)
    - pkgconfig(uuid)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-cursor)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    - pkgconfig(xcb-errors)
    - pkgconfig(xcb-ewmh)
    - pkgconfig(xcb-icccm)
    - pkgconfig(xcb-util)
    - pkgconfig(xcursor)
    - pkgconfig(xkbcommon)
    - pkgconfig(xwayland)
rundeps    :
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-hyprland
setup      : |
    rm -rf subprojects/hyprland-protocols
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
