name       : cmus
version    : 2.11.0
release    : 23
source     :
    - https://github.com/cmus/cmus/archive/refs/tags/v2.11.0.tar.gz : 2bbdcd6bbbae301d734214eab791e3755baf4d16db24a44626961a489aa5e0f7
homepage   : https://cmus.github.io/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Small, fast and powerful console music player for Unix-like operating systems
description: |
    Small, fast and powerful console music player for Unix-like operating systems
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(ao)
    - pkgconfig(faad2)
    - pkgconfig(flac)
    - pkgconfig(libavformat)
    - pkgconfig(libcddb)
    - pkgconfig(libcdio)
    - pkgconfig(libcue)
    - pkgconfig(libmodplug)
    - pkgconfig(libpulse)
    - pkgconfig(mad)
    - pkgconfig(opusfile)
    - pkgconfig(samplerate)
    - pkgconfig(systemd)
    - pkgconfig(vorbis)
    - pkgconfig(wavpack)
    - libiconv-devel
setup      : |
    ./configure prefix=/usr libdir=%libdir% CONFIG_JACK=n
build      : |
    %make
install    : |
    %make_install
