name       : kf6-kwallet
version    : 5.248.0
release    : 3
source     :
    - https://download.kde.org/unstable/frameworks/5.248.0/kwallet-5.248.0.tar.xz : e8f94e7e32c7e7edcf48d4b4b7d2ed50406f601a00e5ad3b9176f821ac490ee2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-3.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Safe desktop-wide storage for passwords
description: |
    This framework contains two main components:
    * Interface to KWallet, the safe desktop-wide storage for passwords on KDE work spaces.
    * The kwalletd used to safely store the passwords on KDE work spaces.
builddeps  :
    - pkgconfig(libgcrypt)
    - gpgme-qt-devel
    - kf6-kcolorscheme-devel
    - kf6-kconfig-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
    - kf6-kwidgetsaddons-devel
    - kf6-kwindowsystem-devel
    - qca-qt6-devel
clang      : yes
optimize   : lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
