name       : plasma-vault
version    : 5.92.0
release    : 64
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-vault-5.92.0.tar.xz : 25df0604f2dca6050606989f240933f051fe9e9d6c31ba8208a8f1debff2afff
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde
summary    : Plasma applet and services for creating encrypted vaults
description: |
    Plasma Vault is a plasmoid for creating and managing encrypted vaults
builddeps  :
    - pkgconfig(libnm)
    - pkgconfig(Qt6Quick)
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-kitemmodels-devel
    - kf6-kpackage-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - libplasma-devel
    - plasma-activities-devel
rundeps    :
    - cryfs
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
