name       : libselinux
version    : '3.7'
release    : 5
source     :
    - https://github.com/SELinuxProject/selinux/releases/download/3.7/libselinux-3.7.tar.gz : ea03f42d13a4f95757997dba8cf0b26321fac5d2f164418b4cc856a92d2b17bd
homepage   : https://github.com/SELinuxProject/selinux
license    : Public-Domain
component  :
    - security.library
    - utils : security.library
summary    :
    - SELinux runtime library
    - utils : Command line utilities for SELinux
description: |
    Main runtime library and API for the SELinux Linux Security Module. This package is provided in Solus with the sole purpose of providing ABI compatibility with "classic Snaps" in order for them to run freely on more platforms without limitation. Solus does not use SELinux within the kernel, the role of `LSM` is given to the AppArmor subsystem.
patterns   :
    - utils :
        - /usr/sbin
        - /usr/share/man
    - devel : /usr/share/man/man3
builddeps  :
    - pkgconfig(libsepol)
build      : |
    %make SHLIBDIR=%libdir% LIBDIR=%libdir%
install    : |
    %make_install SHLIBDIR=%libdir% LIBDIR=%libdir%
