name       : freeciv
version    : 3.1.3
release    : 41
source     :
    - https://files.freeciv.org/stable/freeciv-3.1.3.tar.xz : 741086fa94574374c7c27480f77ee68e5b538bfb2eff85004fa8c87b312c7f2f
license    : GPL-2.0-or-later
homepage   : https://www.freeciv.org/
component  : games.strategy
summary    : Free and Open Source empire-building strategy game inspired by the history of human civilization
description: |
    Free and Open Source empire-building strategy game inspired by the history of human civilization.
libsplit   : no
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(bzip2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(sqlite3)
setup      : |
    %autogen
    %configure --disable-static \
        --enable-client=gtk3 \
        --enable-fcdb=sqlite3 \
        --enable-fcmp=gtk3 \
        --enable-ipv6=yes \
        --enable-sdl-mixer=sdl2 \
        --enable-shared \
        --with-readline
build      : |
    %make
install    : |
    %make_install
