name       : freefilesync
version    : '13.1'
release    : 5
source     :
    - https://freefilesync.org/download/FreeFileSync_13.1_Source.zip : c6e25039e8266473ec0a6254d9a9130f89d0874e4cfaba678d05447abdf74829
license    : GPL-3.0-or-later
component  : network.util
summary    : Free backup software to synchronize files and folders
description: |
    FreeFileSync is a folder comparison and synchronization software that creates and manages backup copies of all your important files.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libssh2)
    - pkgconfig(sm)
    - pkgconfig(xxf86vm)
    - libboost-devel
    - wxwidgets-devel
setup      : |
    pushd ..
    %apply_patches
    popd
build      : |
    %make -C Source exeName=FreeFileSync
    %make -C Source/RealTimeSync exeName=RealTimeSync
install    : |
    #%make_install -C Source
    #%make_install -C Source/RealTimeSync

    install -Dm00755 $workdir/Build/Bin/FreeFileSync $installdir/usr/bin/FreeFileSync
    install -Dm00755 $workdir/Build/Bin/RealTimeSync $installdir/usr/bin/RealTimeSync
    install -Dm00644 $pkgfiles/FreeFileSync.desktop $installdir/usr/share/applications/FreeFileSync.desktop
    install -Dm00644 $pkgfiles/RealTimeSync.desktop $installdir/usr/share/applications/RealTimeSync.desktop

    #unzip Build/Resources.zip FreeFileSync.png RealTimeSync.png
    mkdir $installdir/usr/share/FreeFileSync
    install -Dm00644 $workdir/Build/Resources/* $installdir/usr/share/FreeFileSync
    install -Dm00644 $pkgfiles/FreeFileSync.png $installdir/usr/share/pixmaps/FreeFileSync.png
    install -Dm00644 $pkgfiles/RealTimeSync.png $installdir/usr/share/pixmaps/RealTimeSync.png
