name       : ktextwidgets
version    : 5.115.0
release    : 74
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/ktextwidgets-5.115.0.tar.xz : 6348888c0cc0a37045337f09d71a28f2fd275dfa2258e5ed4e5342f310a39d8e
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Text editing widgets.
description: |
    Text editing widgets.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5TextToSpeech)
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - sonnet-devel
rundeps    :
    - devel :
        - ki18n-devel
        - sonnet-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
