name       : hyprland-protocols
version    : 0.4.0
release    : 2
source     :
    - https://github.com/hyprwm/hyprland-protocols/archive/refs/tags/v0.4.0.tar.gz : ab3525d8bad576db911d4ba1b586f303dd988660b3b8980022c1795fd574b165
homepage   : https://github.com/hyprwm/hyprland-protocols
license    : BSD-3-Clause
component  : desktop-hyprland
summary    : Wayland protocol extensions for Hyprland
description: |
    Wayland protocol extensions for Hyprland. This repository exists in an effort to bridge the gap between Hyprland and KDE/Gnome's functionality. Since wlr-protocols is closed for new submissions, and wayland-protocols is very slow with changes, this repo will hold protocols used by Hyprland to bridge the aforementioned gap.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
