name       : kdesu
version    : 5.115.0
release    : 72
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kdesu-5.115.0.tar.xz : 03e2b7963bc02492639193d20c76723430d5f530b6dee60d61b8dd64f0698b62
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-only
    - LGPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.tools
summary    : User interface for running shell commands with root privileges
description: |
    User interface for running shell commands with root privileges.
optimize   : lto
builddeps  :
    - pkgconfig(x11)
    - ki18n-devel
    - kpty-devel
    - kservice-devel
rundeps    :
    - devel :
        - kpty-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON -DKDESU_USE_SUDO_DEFAULT=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
