name       : k3b
version    : 24.08.3
release    : 89
source     :
    - https://download.kde.org/stable/release-service/24.08.3/src/k3b-24.08.3.tar.xz : bc97c34afb2138ca1fc25bd5fa79e77d1ca2dbe145332317159ef1afbca2c19f
homepage   : https://kde.org/applications/multimedia/org.kde.k3b
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.multimedia
summary    : K3b - The CD Kreator
description: |
    Full-featured CD/DVD/Blu-ray burning and ripping application.
builddeps  :
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(dvdread)
    - pkgconfig(flac)
    - pkgconfig(libavformat)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - kf6-karchive-devel
    - kf6-kauth-devel
    - kf6-kcmutils-devel
    - kf6-kdoctools-devel
    - kf6-kfilemetadata-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-solid-devel
    - lame-devel
    - libkcddb-devel
    - libmad-devel
rundeps    :
    - cdrdao
    - cdrtools
    - dvd_rw-tools
    - sox
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rfv $installdir/usr/share/doc
