name       : opera-stable
version    : 114.0.5282.185
release    : 316
source     :
    - https://get.geo.opera.com/pub/opera/desktop/114.0.5282.185/linux/opera-stable_114.0.5282.185_amd64.deb : f938bcc6a8df93e9dc4defdd3ddb7291a0f7ba85abecc8f0c301f6b7103d1106
license    : Distributable
homepage   : https://www.opera.com
extract    : no
strip      : no
component  : network.web.browser
summary    : The Opera browser brings you more speed, more discoveries and more safety on the web - all for free
description: |
    The Opera browser brings you more speed, more discoveries and more safety on the web - all for free.
patterns   : /*
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt6Core)
    - pkgconfig(alsa)
    - pkgconfig(cups)
    - pkgconfig(gbm)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - ffmpeg-chromium-opera
rundeps    :
    - ffmpeg-chromium-opera
setup      : |
    ar xf $sources/opera-stable_${version}_amd64.deb
    mkdir root
    tar xf data.tar.xz -C root
install    : |
    pushd $workdir/root
        chown root:root usr/lib/x86_64-linux-gnu/opera/opera_sandbox
        chmod 4755 usr/lib/x86_64-linux-gnu/opera/opera_sandbox
    popd

    install -dm00755 $installdir/usr/bin
    install -dm00644 $installdir/usr/lib
    install -dm00644 $installdir/usr/share
    cd root
    mv usr/lib/x86_64-linux-gnu/* $installdir/usr/lib/
    rm -r usr/share/lintian
    mv usr/share/* $installdir/usr/share/
    ln -s /usr/lib/opera/opera $installdir/usr/bin/opera

    # Use system chromium ffmpeg
    rm $installdir/usr/lib/opera/libffmpeg.so
