name       : kactivitymanagerd
version    : 5.92.0
release    : 91
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/kactivitymanagerd-5.92.0.tar.xz : 469c27e060826a470a50d3d71bb466ad125a5c4a9856d73832392a46df304d1f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
component  : desktop.kde.core
summary    : Core components for the KDE Activity concept
description: |
    Core components for the KDE Activity concept.
libsplit   : no
optimize   : lto
builddeps  :
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kglobalaccel-devel
    - kf6-kio-devel
    - kf6-kxmlgui-devel
    - libboost-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
