name       : ada
version    : 2.9.2
release    : 2
source     :
    - https://github.com/ada-url/ada/archive/refs/tags/v2.9.2.tar.gz : f41575ad7eec833afd9f6a0d6101ee7dc2f947fdf19ae8f1b54a71d59f4ba5ec
homepage   : https://github.com/ada-url/ada
license    : Apache-2.0
component  : programming.library
summary    : URL parser written in modern C++
description: |
    WHATWG-compliant and fast URL parser written in modern C++
clang      : yes
optimize   : thin-lto
networking : yes
setup      : |
    sed -e "s|@@VERSION@@|$version|g" $pkgfiles/ada.pc.in > ada.pc

    %cmake_ninja -DBUILD_SHARED_LIBS=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    # pkg-config
    install -Dm00644 ada.pc -t $installdir/usr/lib64/pkgconfig/
