name       : eopkg4
version    : 4.0.0
release    : 1
source     :
    - git|https://github.com/getsolus/eopkg : 38e98ba789d124bec649141ee569bb472832d813
homepage   : https://github.com/getsolus/eopkg
license    : GPL-2.0-or-later
component  : system.base
summary    : "Python3 port of eopkg/pisi. WARNING: For testing only."
description: |
    Python3 port of eopkg/pisi. WARNING: this is for testing only and may break your system!
builddeps  :
    - python-installer
    - python-build
    - python-wheel
    - python-lxml
    - python-packaging
    - python-magic
setup      : |
    %patch -p1 -i $pkgfiles/0001-Use-different-database.patch
    %python3_setup
install    : |
    %python3_install
    for file in eopkg lseopkg uneopkg; do
        mv $installdir/usr/bin/$file $installdir/usr/bin/${file}4
    done