name       : qt6-multimedia
version    : 6.7.3
release    : 14
source     :
    - https://download.qt.io/official_releases/qt/6.7/6.7.3/submodules/qtmultimedia-everywhere-src-6.7.3.tar.xz : 304d28b8e592435293893b0110d5f3534407604d1e04d8a0b0e5b34afe577303
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
homepage   : https://www.qt.io
summary    : Qt6 Multimedia Components
description: |
    Qt Multimedia is an essential module that provides a rich set of QML types and C++ classes to handle multimedia content. It also provides necessary APIs to access the camera and radio functionality. The included Qt Audio Engine provides types for 3D positional audio playback and content management.
builddeps  :
    - pkgconfig(Qt6Qml)
    - pkgconfig(Qt6Quick3D)
    - pkgconfig(Qt6ShaderTools)
    - pkgconfig(Qt6Svg)
    - pkgconfig(alsa)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(libavcodec)
    - pkgconfig(libpulse)
    - pkgconfig(xext)
    - pkgconfig(xrandr)
rundeps    :
    - devel :
        - gstreamer-1.0-plugins-bad-devel
clang      : yes
optimize   :
    - speed
    - thin-lto
setup      : |
    %cmake_ninja \
                 -DCMAKE_MESSAGE_LOG_LEVEL=STATUS
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
patterns   :
    - demos :
        - /usr/lib64/qt6/examples
