name       : plasma-pa
version    : 5.92.0
release    : 93
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-pa-5.92.0.tar.xz : 8c65a2f384f6948712e13560f6bccf8906a7d210e61a19580d660d7b5c5edecd
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for audio volume management using PulseAudio.
description: |
    Plasma applet for audio volume management using PulseAudio.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(libpulse)
    - kf6-kcmutils-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kdeclarative-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-ki18n-devel
    - kf6-kirigami-devel
    - kf6-knotifications-devel
    - kf6-kpackage-devel
    - kf6-kstatusnotifieritem-devel
    - kf6-ksvg-devel
    - kf6-kwindowsystem-devel
    - libplasma-devel
rundeps    :
    - kf6-kirigami
    - sound-theme-freedesktop
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
    rm -rf $installdir/usr/share/doc/HTML
