name       : python-pysol-cards
version    : 0.18.0
release    : 13
source     :
    - https://files.pythonhosted.org/packages/source/p/pysol_cards/pysol_cards-0.18.0.tar.gz : 29196eadd51a54a7bf853d0aecba168853903a24803b8554713e8c7fcc732c2c
homepage   : https://github.com/shlomif/pysol_cards
license    : MIT
component  : programming.python
summary    : Deal PySol FC Cards
description: |
    The pysol-cards python modules allow the python developer to generate the initial deals of some PySol FC games. It also supports PySol legacy deals and Microsoft FreeCell/Freecell Pro deals.
builddeps  :
    - pbr
build      : |
    %python3_setup
install    : |
    %python3_install
