name       : ksshaskpass
version    : 5.92.0
release    : 90
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/ksshaskpass-5.92.0.tar.xz : 844aa7e4c157d9f6dcab265d2a58913d5564f7a260d3bbc96dacb5e1c90f2124
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Front-end for ssh-add which stores the password of the ssh key in KWallet
description: |
    Front-end for ssh-add which stores the password of the ssh key in KWallet.
optimize   : lto
builddeps  :
    - kf6-kcoreaddons-devel
    - kf6-kdoctools-devel
    - kf6-ki18n-devel
    - kf6-kwallet-devel
    - kf6-kwidgetsaddons-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
