name       : libksysguard
version    : 5.92.0
release    : 92
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/libksysguard-5.92.0.tar.xz : b0de5bdded7d45a0091222a9761cdb3526390b28766b166ba3fed34dff2bfd5c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-only
component  : programming.library
summary    : Task management and system monitoring library
description: |
    Task management and system monitoring library.
optimize   : lto
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(Qt6WebEngineWidgets)
    - pkgconfig(xres)
    - kf6-kauth-devel
    - kf6-kglobalaccel-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-knewstuff-devel
    - lm_sensors-devel
    - libplasma-devel
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
