name       : konsole
version    : 24.01.90
release    : 78
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/konsole-24.01.90.tar.xz : 300b9c41bddb267d7a0cc260102c5bb0449a912699eea2a88cacbf8f4eccb231
homepage   : https://kde.org/applications/system/org.kde.konsole
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : KDE's terminal emulator
description: |
    Konsole is a terminal program for KDE. As well as being a standalone program, it is also used by other KDE programs such as the Kate editor and KDevelop development environment to provide easy access to a terminal window.
patterns   : /usr/lib64/libkdeinit*.so
builddeps  :
    - pkgconfig(Qt6Core5Compat)
    - pkgconfig(Qt6Multimedia)
    - pkgconfig(icu-i18n)
    - pkgconfig(x11)
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kglobalaccel-devel
    - kf6-kguiaddons-devel
    - kf6-kiconthemes-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-knotifyconfig-devel
    - kf6-kparts-devel
    - kf6-kpty-devel
    - kf6-ktextwidgets-devel
setup      : |
    %apply_patches
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove docs
    rm -rf $installdir/usr/share/doc
