name       : plasma-thunderbolt
version    : 5.92.0
release    : 52
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/plasma-thunderbolt-5.92.0.tar.xz : 939a6b6c5835cac1580d8e120af4c67693ca1e046dc55c14e43c2af227fff483
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.kde.core
summary    : Plasma integration for controlling Thunderbolt devices
description: |
    Plasma integration for controlling Thunderbolt devices
optimize   : lto
libsplit   : no
builddeps  :
    - kf6-kcmutils-devel
    - kf6-kconfigwidgets-devel
    - kf6-kcoreaddons-devel
    - kf6-kdbusaddons-devel
    - kf6-kdeclarative-devel
    - kf6-ki18n-devel
    - kf6-knotifications-devel
rundeps    :
    - bolt
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml6_cache
