name       : ansible
version    : 2.18.0
release    : 54
source     :
    - https://github.com/ansible/ansible/archive/refs/tags/v2.18.0.tar.gz : 7b05c060502bf0d792a23502803a5ca2189ece25d0c8653339805e54671cf6a9
license    : GPL-3.0-or-later
homepage   : https://www.ansible.com/
component  : system.utils
summary    : Ansible is a radically simple IT automation system
description: |
    Ansible is a radically simple IT automation system
builddeps  :
    - pkgconfig(python3)
    - asciidoc
    - python-build
    - python-docutils
    - python-installer
    - python-jinja
rundeps    :
    - python-jinja
    - python-jmespath
    - python-paramiko
    - python-resolvelib
    - pyyaml
build      : |
    %python3_setup
install    : |
    %python3_install
