name       : mpv
homepage   : https://mpv.io/
version    : 0.39.0
release    : 121
source     :
    - https://github.com/mpv-player/mpv/archive/refs/tags/v0.39.0.tar.gz : 2ca92437affb62c2b559b4419ea4785c70d023590500e8a52e95ea3ab4554683
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  :
    - multimedia.video
    - libs : multimedia.library
    - libs-devel : programming.devel
summary    : mpv is a free (as in freedom) media player for the command line. It supports a wide variety of media file formats, audio and video codecs, and subtitle types.
description: |
    mpv is a media player based on MPlayer and mplayer2. It supports a wide variety of video file formats, audio and video codecs, and subtitle types. Special input URL types are available to read input from a variety of sources other than disk files. Depending on platform, a variety of different video and audio output methods are supported.
mancompress: yes
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(dvdnav)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gbm)
    - pkgconfig(libarchive)
    - pkgconfig(libass)
    - pkgconfig(libavcodec)
    - pkgconfig(libbluray)
    - pkgconfig(libcdio_paranoia)
    - pkgconfig(libjpeg)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(libplacebo)
    - pkgconfig(libpulse)
    - pkgconfig(libva)
    - pkgconfig(luajit)
    - pkgconfig(rubberband)
    - pkgconfig(spirv-cross-c-shared)
    - pkgconfig(uchardet)
    - pkgconfig(vapoursynth)
    - pkgconfig(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(xkbcommon)
    - pkgconfig(xpresent)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xv)
    - python-docutils
rundeps    :
    - libs :
        - yt-dlp
    - libs-devel :
        - mpv-libs
    - yt-dlp
patterns   :
    - libs :
        - /usr/lib64/lib*.so.*
    - libs-devel :
        - /usr/include
        - /usr/lib64/lib*.so
        - /usr/lib64/pkgconfig
replaces   :
    - libs-devel : mpv-devel
environment: |
    export CFLAGS="$CFLAGS -DNDEBUG"
setup      : |
    %apply_patches
    %meson_configure \
        -Dcdda=enabled \
        -Ddvbin=enabled \
        -Ddvdnav=enabled \
        -Dgl-x11=enabled \
        -Dlibmpv=true
build      : |
    %ninja_build
install    : |
    %ninja_install
