name       : gstreamer-editing-services
version    : 1.24.9
release    : 42
source     :
    - https://gstreamer.freedesktop.org/src/gst-editing-services/gst-editing-services-1.24.9.tar.xz : 07506e53bec6c54ec1dfaa5033bad8df42d2f217451822b4c8bf783ef8a27012
homepage   : https://gstreamer.freedesktop.org
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.gstreamer
summary    : Library for creating audio/video editors
description: |
    The "GStreamer Editing Services" is a library to simplify the creation of multimedia editing applications. Based on the GStreamer multimedia framework and the GNonLin set of plugins, its goals are to suit all types of editing-related applications.
builddeps  :
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(python3)
checkdeps  :
    - xorg-server-xvfb
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    export XDG_RUNTIME_DIR="$(mktemp -p $(pwd) -d xdg-runtime-XXXXXX)"
    export MESA_SHADER_CACHE_DIR=$XDG_RUNTIME_DIR/.cache
    GST_GL_WINDOW=x11 xvfb-run -d -s "-screen 0 1024x768x24"  %ninja_check || cat solusBuildDir/meson-logs/testlog.txt
