name       : ksystemstats
version    : 5.92.0
release    : 27
source     :
    - https://download.kde.org/unstable/plasma/5.92.0/ksystemstats-5.92.0.tar.xz : a1eab948b559c221a5d95207da224602bdc1241ffc92991dbe53d00fa2747a29
homepage   : https://invent.kde.org/plasma/ksystemstats
license    :
    - GPL-2.0-only
    - GPL-2.0-or-later
    - GPL-3.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : A plugin based system monitoring daemon
description: |
    A plugin based system monitoring daemon
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig(libnm)
    - kf6-kdbusaddons-devel
    - kf6-kiconthemes-devel
    - kf6-kio-devel
    - kf6-networkmanager-qt-devel
    - libksysguard-devel
    - lm_sensors-devel
rundeps    :
    - libksysguard
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install
