name       : baloo-widgets
version    : 24.01.90
release    : 71
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/baloo-widgets-24.01.90.tar.xz : 15ed315947dc988db665f510754b81bbaa965708c256c0bfe8570ce66e68b110
homepage   : https://community.kde.org/Baloo
license    : LGPL-2.1-only
component  : desktop.kde
summary    : Widgets for the Baloo search engine
description: |
    Widgets for the Baloo search engine.
optimize   : lto
builddeps  :
    - kf6-baloo-devel
    - kf6-kio-devel
setup      : |
    %cmake_kf6 -DBUILD_WITH_QT6=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
