name       : dolphin
version    : 24.01.90
release    : 83
source     :
    - https://cdn.download.kde.org/unstable/release-service/24.01.90/src/dolphin-24.01.90.tar.xz : f524cd10c52c4a6a7b52278d787bc1a8254cb9d0eb28d333096fa88597cbdbe1
homepage   : https://kde.org/applications/system/org.kde.dolphin
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE file manager focusing on usability
description: |
    Dolphin is a file manager focusing on usability. Focusing on usability means that features are discoverable and efficient to use.
patterns   :
    - /usr/lib64/libkdeinit5*.so
builddeps  :
    - pkgconfig(phonon4qt6)
    - baloo-widgets-devel
    - kf6-baloo-devel
    - kf6-kcmutils-devel
    - kf6-kcrash-devel
    - kf6-kdbusaddons-devel
    - kf6-kdoctools-devel
    - kf6-kiconthemes-devel
    - kf6-knewstuff-devel
    - kf6-knotifications-devel
    - kf6-kparts-devel
    - kf6-ktextwidgets-devel
    - plasma-activities-devel
rundeps    :
    - ffmpegthumbs
    - kdialog
    - ruby
setup      : |
    %cmake_kf6
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
