name       : luajit
version    : 2.1.1731601260
release    : 14
source     :
    - https://repo.or.cz/luajit-2.0.git/snapshot/fe71d0fb54ceadfb5b5f3b6baf29e486d97f6059.tar.gz : 1f12f67944431d2b54646404fc41f159c2c66c3f69cd6938de1195f17aa702da
homepage   : https://luajit.org
license    : MIT
summary    : Just-in-time compiler and drop-in replacement for Lua 5.1
component  : programming.library
description: |
    Just-in-time compiler and drop-in replacement for Lua 5.1
builddeps  :
    - git
build      : |
    %make amalg PREFIX=/usr INSTALL_LIB=$installdir/%libdir%
install    : |
    %make_install PREFIX=/usr INSTALL_LIB=$installdir/%libdir%

    # Some build systems need an unversioned symlink to LuaJIT interpreter
    ln -sf luajit-$version $installdir/usr/bin/luajit
    rmdir $installdir/%libdir%/lua/5.1
    rmdir $installdir/%libdir%/lua
    rmdir $installdir/usr/share/lua/5.1
    rmdir $installdir/usr/share/lua
    rm $installdir/usr/lib64/libluajit-5.1.a ## `go-task check` complained
