name       : kauth
version    : 5.115.0
release    : 81
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.115/kauth-5.115.0.tar.xz : 53a9f56befc66a467ea1764af55dfaac0d79a5d5b55d2abe6e399236f9f35aa2
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - LGPL-2.1-or-later
component  : desktop.library
summary    : Execute actions as privileged user.
description: |
    Execute actions as privileged user.
optimize   : lto
builddeps  :
    - pkgconfig(polkit-qt5-1)
    - kcoreaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
