name       : libheif
version    : 1.19.3
release    : 44
source     :
    - https://github.com/strukturag/libheif/releases/download/v1.19.3/libheif-1.19.3.tar.gz : 1e6d3bb5216888a78fbbf5fd958cd3cf3b941aceb002d2a8d635f85cc59a8599
license    : LGPL-3.0-or-later
homepage   : https://github.com/strukturag/libheif
component  : multimedia.codecs
summary    : libheif is an ISO/IEC 23008-12:2017 HEIF and AVIF (AV1 Image File Format) file format decoder and encoder
description: |
    HEIF is a new image file format employing HEVC (h.265) or AV1 image coding, respectively, for the best compression ratios currently possible.
    libheif makes use of libde265 for the actual image decoding and x265 for encoding. For AVIF, libaom, dav1d, rav1e, or SVT-AV1 are used as codecs.
builddeps  :
    - pkgconfig(SvtAv1Enc)
    - pkgconfig(aom)
    - pkgconfig(dav1d)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(libde265)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(rav1e)
    - pkgconfig(x265)
setup      : |
    %cmake_ninja -DWITH_DAV1D=ON \
                 -DWITH_DAV1D_PLUGIN=OFF \
                 -DWITH_RAV1E=ON \
                 -DWITH_RAV1E_PLUGIN=OFF \
                 -DWITH_SvtEnc=ON \
                 -DWITH_SvtEnc_PLUGIN=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
