name       : abseil-cpp
version    : '20230802.1'
release    : 7
source     :
    - https://github.com/abseil/abseil-cpp/archive/refs/tags/20230802.1.tar.gz : 987ce98f02eefbaf930d6e38ab16aa05737234d7afbab2d5c4ea7adbe50c28ed
homepage   : https://abseil.io/
license    : Apache-2.0
component  : programming.library
summary    : Abseil Common Libraries
description: |
    Collection of C++ library code designed to augment the C++ standard library.
emul32     : yes
builddeps  :
    pkgconfig(gtest)
setup      : |
    if [ -z "${EMUL32BUILD+set}" ]; then
        extra_args="-DABSL_USE_EXTERNAL_GOOGLETEST=ON -DABSL_FIND_GOOGLETEST=ON -DABSL_BUILD_TEST_HELPERS=ON -DABSL_BUILD_TESTING=ON"
    fi

    %cmake_ninja \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_CXX_STANDARD=20 \
        -DABSL_CXX_STANDARD=20 \
        -DABSL_PROPAGATE_CXX_STD=ON \
        $extra_args
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    ctest solusBuildDir
